### ISSUE TITLE
Why does function parameter 1 / hotSpotDiv return undefined?

### ISSUE THREAD

**Issue by epignosis567** [mpetroff/pannellum#1000]
Hi. I'm trying to understand why hotSpotDiv in a click handler returns undefined when I console log it. I'm trying to use it to temporarily disable reclicking on the hotspot until the fadeOut animation has finished:

```javascript
        function flashImageAndSound(hotSpotDiv, args) {
            let img = document.getElementById("overlayImgFlash");
            let rndInt = Math.floor(Math.random() * args.length);
            console.log(rndInt);
            
                img.setAttribute('src',args[rndInt]);
                img.style.display = "block";
                img.style.animationName = "fadeOut";
                hotSpotDiv.style.pointerEvents = "none";
            
            img.onanimationend = () => {
                img.style.display = "none";
                img.style.animationName = "";
                hotSpotDiv.style.pointerEvents = "auto";
            };
        }
````

But I get the following error:

`
Uncaught TypeError: Cannot set property 'pointerEvents' of undefined
    at Object.flashImageAndSound [as clickHandlerFunc] 
`

**Comment by mpetroff** [comment]
As stated in the documentation, the first argument passed to the click handler function is the event object. As this is not the hot spot `<div>`, it doesn't have a `.style` property, which is why you can't set `.style.pointerEvents`. You can access the element that was clicked on via the event's [`.target` property](https://developer.mozilla.org/en-US/docs/Web/API/Event/target).
