### ISSUE TITLE
Illegal invocation in opera

### ISSUE THREAD

**Issue by szczemp** [mpetroff/pannellum#1022]
In opera normal mode i cant use pannellum in tour option. When I click on hotspot to load other panorama in console shows error [https://u.lkn.pl/png/ZrzutNekranuN2021-08-29N114351_HmBJ.png](url) and viewer freezes . In private mode is no error and everything works well.
In other browsers everything works in mormal and private mode. There is no my fault in my html and js code, because tour freezes on pannellum demo page https://pannellum.org/documentation/examples/tour/. I thought problem is in opera addons, but when i switch off all addons, the error was still there.

**Comment by mpetroff** [comment]
You're going to need to provide more information, like a browser version, for example. Opera is based on Chromium, so it should behave like it. The error is in a `noisify` function, which exists in neither Pannellum nor Chromium. Thus, you either actually had an add-on that you didn't actually disable (the fact that it works in private mode suggests that this might be the case), or Opera is making some sort of breaking change to the web platform.

The function name and backtrace suggest that the cause is an `<canvas>` anti-fingerprinting attempt that has a bug in its support  for the `<canvas>` `toDataURL()` function. For example, the "Canvas Fingerprint Defender" add-on containers a function named as such (although I'm not about to install a random add-on just to test it). As Opera's marketing makes no mention of anti-fingerprinting, I suspect the issue is with an add-on.

**Comment by szczemp** [comment]
You are right, the problem is with the canvas anti-fingerprinting addon. I missed turn it off.
