### ISSUE TITLE
I'm having a problem when using config : config.json settings file

### ISSUE THREAD

**Issue by sunhasgothishaton** [mpetroff/pannellum#1045]
Hi

I created a multires and and an index.html in the same directory as config.json with the script code
<script>
pannellum.viewer('panorama', {
	"config": "config.json"
});
</script>

I added the line
"basePath": ".",
to the config.json

When I load index.html in a web browser, it reports "no panorama image was specified"

When I copy the code from config.json to the index.html file, it loads correctly.

Can you help?

**Comment by mpetroff** [comment]
This happens because `config` is a [URL configuration parameter](https://github.com/mpetroff/pannellum/blob/master/doc/url-config-parameters.md), not a [JSON configuration parameter](https://github.com/mpetroff/pannellum/blob/master/doc/json-config-parameters.md). The behavior you're describing is exactly what's expected per the documentation, since there's no JSON configuration parameter named `config`. A separate JSON configuration file is only directly supported by the standalone HTML viewer, not by the API. If you want to use a separate JSON configuration file with the API, you need to load it yourself and pass it to the API as a JavaScript object / dictionary.
