### ISSUE TITLE
Image loading with blur effect

### ISSUE THREAD

**Issue by vlkpa** [mpetroff/pannellum#1046]
Hello, is there a way how to change default image loading? Progressive image loading with 
[blur effect](https://raw.githubusercontent.com/dombrant/blurry-image-load/master/img/blur-effect.gif) could be nice feature

**Comment by mpetroff** [comment]
See #766. If you use Pannellum's multi-resolution format, the panorama will be loaded progressively and will only load the resolution that's actually needed. Unfortunately, there's currently no good way to support partially-loaded progressive JPEGs in JavaScript, so that isn't an option (although the image decoding portion of [WebCodecs](https://w3c.github.io/webcodecs/) would support this).
