### ISSUE TITLE
[Q] Multires conversion size ratio and methods to reduce size on disk.

### ISSUE THREAD

**Issue by INF800** [mpetroff/pannellum#1058]
> Note: I am converting hundreds of equirectangular images to multires format. So, I want to store multires converted images as efficiently as possible.

I have `4.7M` sized equirectangular image `0000000000.jpg` and while converting them to multires format, this is how the size on disk looks like for sub directories.

```
6.5M    ./0000000000/4
736K    ./0000000000/2
204K    ./0000000000/1
2.3M    ./0000000000/3
11M     ./0000000000
```

i.e `4.7M` turned into `11M` size.

So, my questions are

1. How to calculate ratio by which size increases.
2. How to reduce size of multires converted images without decreasing levels. Is there even a way to do it (already implemented / not implemented) ?

**Comment by INF800** [comment]
The way I see it is -- size is increasing as levels (subfolder number) increase. So, it looks like we cannot reduce the size on disk.

**Comment by mpetroff** [comment]
1. This is dependent on JPEG compression and how it works with the contents of your images, as well as the resolution of your images. There's no easy to calculate the size increase a priori.

2. You're turning one image into a pyramid of images at different resolutions, so yes, the file size will always go up, unless you decrease the image quality. You can decrease the file size by using the `--quality` flag, but I would tend not to make it any lower than the default, due to the resulting loss of image fidelity.

**Comment by INF800** [comment]
Thankyou
