### ISSUE TITLE
ERROR TypeError: f.addEventListener is not a function at (pannellum.js:48)

### ISSUE THREAD

**Issue by ayubUOL** [mpetroff/pannellum#1060]
Hi, I'm using Pannellum JS in Ionic v5 framework. It works fine on browser but when I deploy it on Android device it show me error after picture loading is completed. I really don't understand where I'm doing wrong or it's something related to Pannellum JS.

In constructor, code is like this.
```
if (this.type == 'image_360') {
      let that = this;
      setTimeout(async function () {
        var panoView = document.getElementById('panorama');
        
        pannellum.viewer(panoView, {
          "type": "equirectangular",
          "panorama": 'https://pannellum.org/images/alma.jpg',
          "autoLoad": true
        });
      }, 400)
    }
```
<img width="745" alt="Screen Shot 2022-01-12 at 4 45 46 PM" src="https://user-images.githubusercontent.com/24814955/149134713-ddf0952d-f370-47a7-ac64-137a0ae440be.png">

**Comment by mpetroff** [comment]
Let me start by quoting the readme:
> Mobile / app frameworks are not officially supported. They may work, but they're not tested and are not the targeted platform.

While I can't say with complete certainty what the issue is, since you're using a minified copy (which has mangled variable names), I believe this is because Ionic's reimplementation of `FileReader` is not standards compliant. See #284, #622, and the issues linked to from https://github.com/mpetroff/pannellum/pull/622#issue-336965389.

**Comment by ayubUOL** [comment]
Thank you for quick reply and for useful links. You did a great job by making this JS library. 
I've solved the issue using your provided links. Thanks Again
