### ISSUE TITLE
Occasional CORS failure

### ISSUE THREAD

**Issue by gms384** [mpetroff/pannellum#1069]
I am using Pannellum 2.5.6, and usually it all works beautifully (thanks!).

But I occasionally see a CORS error (in Chrome) where an image does not load, but I do not think it is really a CORS configuration problem, since (a) it works most of the time in Chrome and (b) when it fails in Chrome, I can load the same page and another browser and it works fine.

When it is working, if I look at the HTTP request for the image, it includes a line:

"Remote Address [my ip]"

When it is failing, I do not see that line in the request for the image, which makes me think that occasionally Pannellum (or my browser for some reason) omits it, and then the server of course denies the request, with Javascript error:

Access to XMLHttpRequest at 'https://...' from origin 'https://...' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Any ideas?

Thanks

Greg Saunders

**Comment by gms384** [comment]
FYI:  I think I solved this...it was a very subtle issue.

If you have a 360 image which is also used as a plain old regular HTML image in your site, the browser makes an HTML request for the image first, and since it's not JavaScript related, there's no CORS involved, and there are no access control headers in the reply.  Then when Pannellum requests the image later, it gets a cached version with no CORS headers and breaks.

This happens in Chrome; it is ok in Firefox.  And it took a LONG time to figure out.

**Comment by mpetroff** [comment]
The Chrome developers consider this to be a [server configuration issue](https://bugs.chromium.org/p/chromium/issues/detail?id=409090).

It can be fixed by setting certain headers on the server response (e.g., see [this blog post](https://blog.keul.it/chrome-cors-issue-due-to-cache/)) or by adding `crossorigin="anonymous"` to your `<img>` tag.

Regardless, it's not an issue with Pannellum specifically, so I'm going to close this issue.

**Comment by gms384** [comment]
Thanks for the extra clarification.
