### ISSUE TITLE
removeHotspotId api, hotspotId, number or string

### ISSUE THREAD

**Issue by dbwodlf3** [mpetroff/pannellum#1088]
https://github.com/mpetroff/pannellum/blob/eb50628da1852afa5a1586f88bcd1e01a3e63468/src/js/pannellum.js#L3207

hotspotId and sceneId can have string or number type.
but in the api use "===" exactly equal syntax.
if you didn't purpose it, I think it is better to use "==" expression than it.

**Comment by mpetroff** [comment]
I did it on purpose, since I generally err on the side of strict checking to avoid issues due to type conversion. However, there's no particular need for it in this case, so I relaxed the checks.

The IDs are specified as strings in the documentation, so while numbers may end up working, they're not explicitly supported.
