### ISSUE TITLE
About the pannellum's infospots.

### ISSUE THREAD

**Issue by omarbenjdidia** [mpetroff/pannellum#1103]
Hello, i was wondering if you can do a popup video when you click on the infospot.

**Comment by eyecatchup** [comment]
You can simply configure a video in the hotspot config like so:

```js
hotSpots: [
  {
    pitch: 0.1628639147350518,
    yaw: -43.752909800132414,
    type: "info",
    video: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"
  }
]
```

**Note:** You'll need to apply custom CSS to correctly position video tooltips! Currently the library does not center video tooltips correctly.

Result:

<img width="355" alt="Bildschirmfoto 2022-07-22 um 15 28 15" src="https://user-images.githubusercontent.com/845131/180449250-5377dcdc-6325-4049-bc1e-815fd1c96dd0.png">

**Comment by omarbenjdidia** [comment]
Hello, i've tried it with a youtube video link but nothing shows up ...
![Capture](https://user-images.githubusercontent.com/92368449/180469457-95dadca5-70cf-4da8-83a9-c84986c53b53.JPG)

**Comment by mpetroff** [comment]
> Currently the library does not center video tooltips correctly.

Videos are not officially supported, which is why the `video` parameter isn't documented.

> Hello, i've tried it with a youtube video link but nothing shows up ...

A YouTube link is not a video file, so it wouldn't be expected to work. To embed a YouTube video, you'll have to add `clickHandlerFunc` and `clickHandlerArgs` parameters to your hot spot and write a function to call with these that creates your popup and populates it with appropriate YouTube `<iframe>`.

**Comment by omarbenjdidia** [comment]
thanks alot .
