### ISSUE TITLE
Unable to get correct `northoffset`of 'multires panorama' created from 'Photosphere' using generate.py

### ISSUE THREAD

**Issue by Hfawad** [mpetroff/pannellum#113]
I created Multires panorama from a photosphere, It is not giving correct northoffset.

**Comment by mpetroff** [comment]
The `generate.py` script does not copy metadata from the source panorama. Did you add a `northOffset` parameter to the JSON configuration file it created?

**Comment by Hfawad** [comment]
I am adding Multires panoramas on a click event, so I have to add `northOffset` manually, which is hectic to do, Can you suggest any method to do it so automaticlly?
Multires panorama viewer script is given below :
<pre>
	pannellum.viewer('container', {
		"title": "Multires Testing",
		"type": "multires",
		"autoLoad": true,
		"compass": true,
      <b>    "northOffset":240,</b>
		"multiRes": {
		"basePath": "./multires/"+image_name,
			
			"path": "/%l/%s%y_%x",
			"fallbackPath": "/fallback/%s",
			"extension": "jpg",
			"tileResolution": 512,
			"maxLevel": 4,
			"cubeResolution": 2080	
		}
		});
</pre>

**Comment by mpetroff** [comment]
I'm not sure if you're asking if there's a way to automatically extract the heading information when you generate the multires files from the source image or if you're asking if there's a way to extract the information from the multires files when you display the panorama.

For extracting the heading information from the source image, you could use [exiftool](http://www.sno.phy.queensu.ca/~phil/exiftool/) with the following arguments:
`exiftool -XMP:PoseHeadingDegrees image.jpg`

Since the heading information isn't extracted when the multires files are generated, there's no way to get the heading information from the them.

**Comment by Hfawad** [comment]
Yeah I was looking for method to extract heading information, it help me a lot, Thank you so much.
