### ISSUE TITLE
Video panorama auto load 

### ISSUE THREAD

**Issue by aproni34f** [mpetroff/pannellum#1147]
Is there a way to autoload first frame of the video? I cant even load video panorama automatically, but I dont want video to play, only load first frame. This is my code:

       <video id="panorama" class="video-js vjs-default-skin vjs-big-play-centered"  controls preload="none"  crossorigin="anonymous">   
        <source src="https://pannellum.org/images/video/jfk.webm" type="video/mp4"/>
    </video>

    videojs('panorama', {
    preload:"auto",
    controls: true,
        plugins: {
            pannellum: {autoLoad:true}
       }
    });

https://jsfiddle.net/t8fbyw01/2/

**Comment by mpetroff** [comment]
I assume you want it to be interactive, since the [video example](https://pannellum.org/documentation/examples/video/) already includes a static preview. It can probably be done by using a tour configuration. You'd autoload to a scene configuration with a normal panorama and then have the "play" button use `loadScene()` to switch to a scene that includes the video configuration; this would require making changes to the Video.js plugin.
