### ISSUE TITLE
hotspot size

### ISSUE THREAD

**Issue by almarass1** [mpetroff/pannellum#1150]
Hi,
Is it possible to enlarge hotspots size in order to use them with mobile devices with low screen resolution?

Thanks,
Alex

**Comment by mpetroff** [comment]
Previously, there wasn't an easy way to do this, as the only way was to use [custom hot spots](https://pannellum.org/documentation/examples/custom-hot-spots/).

However, I just modified the [hot spot scale parameter](https://github.com/mpetroff/pannellum/blob/master/doc/json-config-parameters.md#scale-boolean-or-number) to accept a number (previously, it was only a boolean that would scale hot spots based on the zoom level). If you set this on all your hot spots, you can scale them. For example, a hot spot with the configuration
```json
{
    "pitch": -12,
    "yaw": 170,
    "type": "info",
    "text": "Some text.",
    "scale": 2
}
```
will now display as twice the size as normal (and so will the tooltip).

Does this change implement what you had in mind (feel free to reopen, if not)?

**Comment by patrickvane** [comment]
Hi @mpetroff, thank you for this modification, it's great to have this functionality, but the implementation of it is causing a limitation to occur that we're running into.

We'd like to have it scale according to the FOV (so it looks like it's in 3D space rather than a 2D element), but we also like to increase/decrease the size of it depending on the distance towards that spot/location. 

With the modification you've made here, we now have to choose between either it scaling according to the FOV ({"scale":true}), or it scaling according to the distance we have ({"scale":5/distanceInMeters}). We'd like to do both, which isn't currently possible. 

The easiest solution would be if this modification would be its own parameter, something like "scaleMultiplier" or "size". Then we would be able to get our requirements working by doing {"scale":true, "size":5/distanceInMeters}. 

I hope that makes sense.

**Comment by mpetroff** [comment]
@patrickvane Your suggestion on separating out dynamic and fixed scaling is a good one, so I made the change in f361b36a13513c91d86fc68b5c80b15cb64e0d09. I named the new parameter `scaleFactor` instead of `size`.

As for your suggestion of a `zIndex` parameter, I think it's problematic. Hot spots are explicitly sorted by pitch to avoid hot spots from overlapping tooltips, but setting the z-index breaks this. Since the tooltip is a descendant of the hot spot and `z-index` applies to an element's descendants, I don't know a simple away around this.
