### ISSUE TITLE
Is there a way I can manipulate the hot spot? I want to drag the hot spot.

### ISSUE THREAD

**Issue by wuxianhuo** [mpetroff/pannellum#1163]
I am very sorry that my English is poor, so I can only ask you questions with the help of translation tools. I have looked up relevant materials, but I did not find any api that can operate hot spots. I want to add a drag and drop feature to the hotspot. There is no way.

**Comment by mpetroff** [comment]
If you set the `draggable` hot spot configuration parameter to `true`, the hot spot can be dragged. You can then use the `dragHandlerFunc` / `dragHandlerArgs` hot spot configuration parameters to define a function, and arguments to be passed to that function along with the event object, when dragging starts and stops. These are documented in `doc/json-config-parameters.md`.

However, there is currently no example for using these features, and you have to use the Git `master` branch to use them, since they are features that were added since the current v2.5.6 release.
