### ISSUE TITLE
hotspot stransform style error on chrome version 116

### ISSUE THREAD

**Issue by cuongnc5** [mpetroff/pannellum#1175]
After upgrade chrome browser to version 116. Hotspot error when hover on div hotspot
Example: https://simplevirtualtour.it/app/viewer/POIs-error-on-chrome
I found some update in chrome version 116: https://developer.chrome.com/blog/chrome-116-beta/
How to fix this error?

**Comment by mpetroff** [comment]
Care to elaborate? What kind of error? What do you mean by "div hotspot"?

**Comment by cuongnc5** [comment]
> Care to elaborate? What kind of error? What do you mean by "div hotspot"?

I am using the pannellumjs library to build a virtual store for displaying products. After upgrading the Chrome browser from version 115 to version 116, I encountered the following issue:

When hovering over hotspots containing images, the images experience noticeable shaking or jittering. My hypothesis is that this behavior is related to Chrome's update of the CSS transform property and potential changes in the mouseenter and mouseleave events. I found some information about this in the documentation at https://developer.chrome.com/blog/chrome-116-beta/. I suspect that these changes might be affecting the events within the pannellumjs library. I would appreciate it if you could investigate this matter.

Below is an video illustrating the issue:
https://github.com/mpetroff/pannellum/assets/9640740/20b30a72-3344-450d-b978-703810044a6e

And link my website: https://my.vrmall.io/viewer/index.php?code=6c524f9d5d7027454a783c841250ba71

**Comment by mpetroff** [comment]
The hot spots you're having issues with are something you added yourself, by modifying Pannellum. Best I can tell, the issues are not related to Pannellum itself but only with your additions; I can't reproduce the issue with the default hot spots with either the current `master` branch or with v2.5.6.

The issue is not directly related to anything mentioned in the Chrome 116 developer notes. The mouse event changes are not relevant (you get the same shaking at your link if you move the view with the arrow keys), and the CSS motion path feature should not directly cause any issues either. However, it's entirely possible that the Chromium developers broke something when implementing the CSS motion path feature, which caused the regression you see.

Are you absolutely sure you upgraded from v115 and not v114? I found [an issue on the Chromium issue tracker](https://bugs.chromium.org/p/chromium/issues/detail?id=1471225) that looks like it could be related to the issues you're seeing, but it was reported for v115, not v116; of course, it could also be entirely unrelated.

Why should I help you debug an issue with a feature you've added yourself but haven't opened a pull request for and contributed back? You're well within your rights to take my work, extend it, and sell it as you've done, but I'm also under no obligation to help you for free if you do. Regardless of whether or not I should help you, I don't have the code for your added features, making it difficult to see how they work or to debug them.

**Comment by cuongnc5** [comment]
First of all, I apologize for my poor English.
I don't intend to ask you for help debugging. I will close this issue. 
Again, thank you for your support and providing a great library.

**Comment by mpetroff** [comment]
> First of all, I apologize for my poor English.

Your English is fine.

> Again, thank you for your support and providing a great library.

Thanks!

I'd recommend trying to produce a minimal reproducible example. I think the issue is likely due to a browser bug, so a minimal example would allow you to report it to the Chromium developers.
