### ISSUE TITLE
Support for double circle format?

### ISSUE THREAD

**Issue by nh2** [mpetroff/pannellum#118]
Hello,

this is a really nice viewer that you made.

Do you think it would be possible to add support for the double-circle ("dual fish eye") video format that the Ricoh Theta S camera records? It looks like this:

http://theta360developers.github.io/blog/img/2015-12/dual-fish-eye.jpg

So far I haven't found a single working open-source viewer that can play it.

(An alternative would be to convert it to equirectangular first, but I haven't found any software for that either yet, and it would be great if a video player could play the output format directly.)

Thanks!

**Comment by mpetroff** [comment]
Pannellum will never support anything like this since the format is undocumented and specific to the lens distortion of the Ricoh Theta S; I have no desire to add a new renderer for every new panoramic camera that comes along. Additionally, it requires some blending to be performed at the edges, which is somewhat difficult to do in a browser.

The only real solution is to convert the video to equirectangular first. Until someone reverse-engineers the lens distortion (or Ricoh publishes it), we're stuck with Ricoh's Windows/Mac only software.
