### ISSUE TITLE
Cubemap panorama

### ISSUE THREAD

**Issue by zeleamaaa** [mpetroff/pannellum#1215]
Excuse me, I would like to ask if there is an explanation about panorama cubemaps in the example section, such as how to combine the 6 images or is there a reference that I can read to understand how it works? Thank you in advance.

**Comment by mpetroff** [comment]
The six images need to be provided in the order `+z, +x, -z, -x, +y, -y` (this is mentioned in the docstring / API documentation). Otherwise, the format is a standard [OpenGL cubemap](https://www.khronos.org/opengl/wiki/Cubemap_Texture).

There's also a [cube map example](https://pannellum.org/documentation/examples/cube-map/).

However, it's the least well supported format for Pannellum and doesn't include any loading progress indication, so I'd tend to avoid using it (and I keep thinking about deprecating it).
