### ISSUE TITLE
Untilting a panorama

### ISSUE THREAD

**Issue by Ephraim-Bryski** [mpetroff/pannellum#1224]
I'm using pannellum to view panoramas, some of which are tilted. Along with the panoramas, I'm given the orientation of the central camera when the panorama was taken (i.e. the center of the panorama) expressed as a quaternion (which I know can then be converted to a rotation matrix). I also know pannellum has tools to untilt a panorama, namely `setHorizonRoll` and `setHorizonPitch`. However, I'm struggling to go from the rotation matrix to angles I can feed into pannellum. I can use scipy's `Rotation.as_euler` to decompose a rotation matrix into euler angles, which might be promising. However, I can't quite figure out the necessary order of the rotations, and whether they're intrinsic or extrinsic. Does anyone have any pointers on this or any method which has worked for them? Thank you!

**Comment by mpetroff** [comment]
The horizon pitch and roll parameters were added to support Google Photo Sphere XMP metadata, so they follow the convention defined there:
https://developers.google.com/streetview/spherical-metadata#euler_overview

You can also go straight from quaternions to Euler angles. Pannellum uses quaternions internally to deal with the Device Orientation API, so it needs to convert back to Euler angles:

https://github.com/mpetroff/pannellum/blob/83084e892cc3dc0bedc53307fabe6db6acc93937/src/js/pannellum.js#L1697-L1709

These are applied as `pitch = phi`, `roll = -theta`, `yaw = -psi`. You might (probably?) have to flip the signs, since you're trying to undo a rotation instead of apply one.

**Comment by Ephraim-Bryski** [comment]
Thank you! After some work I was able to apply the inverse operations to untilt the panoramas.
