### ISSUE TITLE
Support tiled multi-resolution equirectangular panoramas

### ISSUE THREAD

**Issue by parsnick** [mpetroff/pannellum#142]
Are there any plans to support multi-res panoramas *without* converting to your `generate.py` format?

For context, I'm working on an app that already has multi-res equirectangular tiles for 3000 panoramas, which are displayed as a [custom Google Street Views](https://developers.google.com/maps/documentation/javascript/examples/streetview-custom-tiles). I'd like to migrate to using Panellum instead, but it doesn't seem to be possible without redoing all my existing images.

I've had a look at implementing this and it seems technically feasible - the optional `phiStart, phiLength, thetaStart, thetaLength` arguments to three.js' [`SphereGeometry`](http://threejs.org/docs/#Reference/Extras.Geometries/SphereGeometry) make it fairly easy to build a sphere composed of multiple pieces, each piece showing a different tile. 

(If it's any help, a quick but crap illustration of that: http://parsnick.github.io/panoviewer/ [think I've messed up the texture loading - may take a few refreshes to load everything, and needs click + drag before it starts showing anything])

So I guess there's two overlapping questions:

1. Is there a technical reason that you don't already support equirectangular tiles? The multi-res format that is currently supported appears bespoke(?) and seems like more effort, both to implement and consume.
2. Are there any plans to support equirectangular tiles in future?

And thanks for your work on this!

**Comment by mpetroff** [comment]
Cube maps are a technically superior format since they are an exact representation and are less computationally intensive to display, which is why they are used for video game [skyboxes](https://en.wikipedia.org/wiki/Skybox_%28video_games%29).

Using equirectangular tiles leads to distortions since the sphere is approximated using triangles; these could in theory be fixed by applying the correct distortions to the tiles, like what is done with cube maps, but there's no reason to do this instead of using a cube map, and Google doesn't do this. For example, compare the nadir of this photo on [Google Photos](https://photos.google.com/photo/AF1QipNQo86XpiRwcjX0PJgF2mj8o31o2F7EJGy7B18M) to the nadir of the same photo on [pannellum.org](https://pannellum.org/); the Google version has distortions, while the version displayed in Pannellum does not. Pannellum's regular equirectangular support gets around this by using an exact mathematical mapping from an equirectangular image to a rectilinear view, but this can't easily be used for tiles. The current cube map-based format is also simpler to implement than a spherical approximation, particularly since there's no geometry library being used (and the format is similar to what is used by krpano).

I have no intention of every implementing an equirectangular multires format. If I ever implement another format, it would be based on either [HEALPix](https://en.wikipedia.org/wiki/HEALPix) or a [hierarchical triangular mesh](http://www.skyserver.org/htm/) (I work in astrophysics).

**Comment by Neon22** [comment]
I believe the free version of HDR shop does equirectangular to skybox mapping.
Nona can also be configured to do it. below. So a simple python script could do all of the directories of files in one go.

E.g..
- http://stackoverflow.com/questions/29678510/convert-21-equirectangular-panorama-to-cube-map
- http://vinayhacks.blogspot.co.nz/2010/11/converting-equirectangular-panorama-to.html
- https://groups.google.com/forum/#!topic/hugin-ptx/WD2DRAFl4TQ
keep searching for the language and tools of your choice.
"equirectangular to cubemap"

**Comment by mpetroff** [comment]
The `generate.py` scripts uses `nona` for the conversion from equirectangular to cube map and then uses the Python Pillow package to create tiles from the cube faces.

**Comment by Rickmc3280** [comment]
Does anyone here have an idea how to convert equirectangular image to cubemap, and break it down based on information provided (for example - the moon).  Circumference of the moon is10,921k meters.  So a cubemap would have 4 tiles across the equator and break that down into the nearest power of 2 for tiling  so... 10,921,000/4 = 2,730,250.  2,730,250\x = range of 4096 = grid pattern.  

Or am I thinking about this the wrong way.  Trying to find an algorithm, software to break this up and automate.  Found a software to break up tif data into cubemaps, but having trouble being able to use said data in any terrain software due to the sizes.

**Comment by Neon22** [comment]
https://github.com/sunset1995/py360convert
https://github.com/bhautikj/vrProjector
https://stackoverflow.com/questions/29678510/convert-21-equirectangular-panorama-to-cube-map
