### ISSUE TITLE
Possible memory leaks

### ISSUE THREAD

**Issue by claustres** [mpetroff/pannellum#174]
Hello, first of all thanks for this great library not so usual in JS.

We are using pannellum to interactively display different panoramas alternatively in the same page. Each time we want to display a panorama we create a viewer like this:
`viewer = pannellum.viewer('panorama', config);`

However, it seems that most of the memory used is never freed. Looking at the code we can see that none of the allocated WebGL objects are freed (textures, buffers, etc.). Indeed, although JS objects are probably freed by the garbage collector in my experience there is no garbage collector in WebGL and you need to release the memory by yourself. Maybe its by design because in the `destory()` method of the renderer the WebGL canvas is destroyed, however I am not sure it will ensure the WebGL objects to be destroyed too. Actually by testing this on multiple browser it seems they are not. 

We did some hack in order to retrieve some memory and make our app usable on mobile devices with few memory by calling `destroy()` manually at some point and adding inside the method the following code:
```
for (var i = 0; i < program.currentNodes.length; i++) {
           if (program.currentNodes[i].texture) {
               gl.deleteTexture(program.currentNodes[i].texture)
           }
}
```

We will try to contribute by providing a better solution but any help or advice is welcome. We believe the WebGL canvas should be globally allocated by the library, such as the shaders. Then the renderer object should only manage the objects used to display a panorama and correctly release all of them on destroy.

By the way we are using the multires mode.

**Comment by mpetroff** [comment]
WebGL objects are freed when the corresponding JavaScript object is garbage collected. However, when this garbage collection happens is based on system memory usage, not GPU memory usage, so one can run out of GPU memory.

I just committed 53c6cf85f7eb7c1accf07ab5fd2e23d6251c5151, which explicitly frees multires textures when their parent nodes are destroyed; this might help reduce GPU memory usage. Unfortunately, I don't know of any tools to profile WebGL GPU memory usage to test if it helps. The commit also fixes a DOM object and event listener leak, although I doubt the leak was causing a problem.

A globally allocated canvas is not an option, since this would prevent one from having multiple viewers on the same page. That being said, it should be possible, and would be preferable, to reuse the canvas in a particular viewer instance between scene changes instead of creating a new one each time the scene is changed.

**Comment by claustres** [comment]
Thanks for this rapid fix, actually when I said WebGL objects I effectively meant GPU-side objects.

You are right for a globally allocated canvas, in this case keeping one canvas per renderer seems mandatory. However, it should be possible to change the panorama config on the fly in a viewer so that we don't need to recreate everything to display a new image. Indeed, creating/destroying WebGL context on the fly is probably not a recommanded practise although it should work in theory.

Is there already a way with panellum to change the viewed image inside a viewer without the need to create a new instance  ?

**Comment by mpetroff** [comment]
If you have a list of the panoramas when the viewer is created, the tour syntax can be used ([see example](https://pannellum.org/documentation/examples/tour/)). Dynamically adding to this list isn't currently supported. The [`loadScene`](https://github.com/mpetroff/pannellum/blob/master/src/js/pannellum.js#L2094) method can then be used to switch between the images.

**Comment by claustres** [comment]
OK this might be a viable solution because our list of panoramas is static but can be big (~ 20). Using the tour syntax are panoramas loaded/unloaded on-demand when calling `loadScene` ?

**Comment by mpetroff** [comment]
Yes, they are.

**Comment by mpetroff** [comment]
The renderer is now reused between scenes (see 38250c1d15d4ee3c792ae442336c53f637893f7f).
