### ISSUE TITLE
Roll compensation becomes global?

### ISSUE THREAD

**Issue by MmmDee** [mpetroff/pannellum#181]
Using the Ricoh Theta S which includes roll information, it appears Pannellum reads this and compensates... but only for the first picture, then uses that "correction" globally for subsequent loadScenes and hotspots.  

In the above link, the first image shown, "foyer" (roll of nearly 0) is displayed correctly, but clicking on "backyard" (image has a roll of -2.3 degrees), that image is not compensated. However, if the backyard scene is loaded first, then Pannellum compensates but applies that erroneous compensation to foyer. 

The latest master branch (c268...) was used.  The behavior also manifests in the CDN version using just hotspots, only the first picture's roll is evaluated.  

The hotspot is toward the rear of the first image.

It appears config.ignoreGPanoXMP is always being set true causing the XMP data to be ignored.

Edit: deleted URLs

**Comment by MmmDee** [comment]
I'm withdrawing this issue... if I put ignoreGPanoXMP as the initial config parameter (before default and individual scenes) the "problem" disappears. I "mistakenly" thought it could be  scene argument.

**Comment by mpetroff** [comment]
It's setting `ignoreGPanoXMP` to true because you're setting a parameter that's set by the metadata, `northOffset`. Since the XMP metadata is loaded after the scene settings, it would override any existing settings if applied, so it's disabled if any of the settings it sets are manually specified (`haov`, `vaov`, `vOffset`, or `northOffset`).

The part about the roll setting from the first image being used for all of them (if it's not specifically set by a later image) was a bug, which I just fixed in c649c83326c0b8a968c3491139bc95831f0c2c88.

**Comment by MmmDee** [comment]
While I can appreciate the logic of `haov, vaov and vOffset`causing XMP data to be ignored, I'm not quite as sure about why specifying `northOffset`should do the same. I haven't used the Ricoh Theta S that much, but I suspect the internal compass of the camera is much less reliable than say, the roll sensor.  In the short time I've used the camera, I've come to doubt the accuracy of the built-in compass; however, the roll sensor thus far has seemed quite accurate. I'm going to take some photos later today as an experiment/illustration.  Perhaps setting `northOffset` should simply cause the image's XMP compass data to be ignored, not the whole XMP packet.

And thanks for fixing the bug wherein the first image with XMP data overrode all other images.

**Comment by mpetroff** [comment]
I agree that the compass on the Theta S is pretty bad; if I remember correctly, it only reports the heading in 22.5 degree increments.

The reason the metadata is ignored is due to the internal architecture; otherwise, I'd only have it ignore the specific parameters that were set. The scene parameters are loaded when the transition is triggered; the metadata isn't processed until the image finishes loading. Since nothing keeps track of which parameters are specifically set and which are defaults, either all the metadata has to be used or none of it is.

**Comment by MmmDee** [comment]
Well, that does give some concern regarding images with roll <> 0 and compass errors… though I was unable to get the Theta’s compass to be inaccurate during my testing today. I hadn’t noticed the 22.5 degree resolution of the compass and couldn’t find that listed on the web, but it agrees with observations.

**Comment by MmmDee** [comment]
Turns out to be not such a big deal... I need the roll information in the XMP, so I must have `ignoreGPanoXMP` be false. I've found I can use exiftools (or presumably any XMP editor) to fix the heading/compass data in the image (exiftools is a great command line tool). XMP data is not present in google street view panoids or in images after they've been edited with something like Windows Paint.

**Comment by mpetroff** [comment]
I changed things in 94024f7d343eedef9063e7f4ac3ae03b6ae997ca such that overriding individual XMP set parameters doesn't disable use of the rest of the metadata.

**Comment by MmmDee** [comment]
Thanks Matthew, as always... you're the best. When I have new photos with absent/incomplete/wrong XMP data, I'll give the update a test. Does specifying `northOffset`no longer force `ignoreGPanoZMP:true`?

**Comment by mpetroff** [comment]
Correct.

**Comment by MmmDee** [comment]
I confirmed that `northOffset`no longer forces ignoreGPanoXMP. Is there a way to specify on a per-scene basis, the image roll? I didn't see it in the edits. This might make a nice enhancement for images that contain no XMP data (ie, Google street view tiles). It can be worked around (editing image with exiftools for example), I'm simply curious. Otherwise, I'm comfortable closing the issue.

**Comment by mpetroff** [comment]
The horizon pitch and roll support were originally added to support Ricoh Theta images (the parameters are not part of Google's Photo Sphere XMP data specification), which is why they weren't configurable. Since they could be useful in other cases, I made them configurable in 234201ea41dd9e8fc948690ed371843379b8fcfb.
