### ISSUE TITLE
startAutoRotate and stopAutoRotate functions have troubles ?

### ISSUE THREAD

**Issue by jadoremanger** [mpetroff/pannellum#235]
Hello

1) It seems that the commit :
"Add auto rotation start / stop methods to API"  ivarvong committed with mpetroff on 30 Jun
Is currently not compatible with the autoRotateInactivityDelay parameter.
I mean : when autoRotateInactivityDelay is enabled (on 5000 for example), the stopAutoRotate function doesn't work, the rotation continue **instantly** (no need to wait 5000ms).

2) The stopAutoRotate function doesn't stop at the current position, i dont know why but it does a rotation of something like 90degree just after i call the stopAutoRotate function.

3) startAutoRotate currently doesn't work with " When auto rotate restarts after inactivity, set pitch to zero and return to original HFOV". I think it should be very cool if it does.

**Comment by mpetroff** [comment]
These were all bugs, which I've now fixed. With regard to `autoRotateInactivityDelay`, the `stopAutoRotate()` method now prevents any time-delay based rotation restart, since I think that is the most sensible approach (API calls are not considered interactions and therefore don't reset the inactivity countdown).
