### ISSUE TITLE
Choppy while loading initial tiles

### ISSUE THREAD

**Issue by thorsonmscott** [mpetroff/pannellum#281]
Hey there, thank you so much for sharing your hard work on this library!

I'm using it with multires mode and autoload, with tiles generated by `generate.py`.  I've noticed that right when the page loads, it shows a lower res version of the photosphere, which is desired for fast initial load.  But navigating the around the photosphere with either the mouse on desktop or touch / gyroscope on mobile is pretty choppy for me initially.  I've watched the network tab during this initial load, and as soon as it stops pulling in tile images the navigation snaps back to being super smooth.  I'm assuming this is some kind of lag while all the higher res tiles are loading, likely on the same thread, and after they've loaded it frees up resources for navigation again.

Do you have any tips for optimizing this?  Should I try different settings when generating the tiles or start with an initial hfov that is zoomed out further?

On desktop it is less of an issue, but on mobile it's especially noticeable.

Thanks for any tips you can provide, really appreciate the library!

**Comment by mpetroff** [comment]
This is an issue I have yet to find a solution to. One multires tile is loaded per frame. Since WebGL operations are blocking and have to happen on the main thread, the framerate takes a hit if it takes too long to convert a tile image into a texture and load it into the GPU (the downloading of the images is asynchronous). The one tile per frame limit is the best solution I've come up with; on a fast computer, it makes tile loading take longer, since multiple tiles could otherwise be loaded during one frame, but it causes the least number of dropped frames in general.

As for workarounds, using a smaller tile size, 256px, might help as each tile would be a quarter of the resolution.

**Comment by thorsonmscott** [comment]
Thanks for the response!

I'm finding this issue to only happen when the gyroscope activated.  If I don't use the gyroscope and only navigate using touch, I don't see this issue at all, at the very least it's much much less noticeable.  Do you agree with that? If that's the case, would it have anything to do with gyroscope events firing too quickly?

I have forked the project and am going to start digging around to see what I can find.  I'll try your suggestion of smaller tiles as well to see if that would help.

Thanks again!

**Comment by mpetroff** [comment]
You were right about there being an issue with device orientation control&mdash;it was making too many render calls. I think I fixed it in a30261ca8c68f030f5d7de564d6f252650699c3f, but I've haven't tested the fix yet.

**Comment by thorsonmscott** [comment]
@mpetroff OMG!  That definitely fixed the issue I was having with device orientation, much appreciated!

On a side note, I've made some updates in my fork that expose enabling / disabling the orientation control after initialization and using a combination of touch navigation _and_ relative device orientation.  I'll submit a PR after a little more testing that you can take a look at if interested.

As for this issue, [a30261c](https://github.com/mpetroff/pannellum/commit/a30261ca8c68f030f5d7de564d6f252650699c3f) seems to have fixed the reason I opened the issue, so close at will!

Thanks again, appreciate it big time!
