### ISSUE TITLE
Preloading Scene

### ISSUE THREAD

**Issue by andrade94** [mpetroff/pannellum#282]
Hello good sir, is there a way to preLoad all the scenes when seeing one? For example, I enter the tour and while I'm seeing the first scene can the others be loaded in the background so when I change of scene it won't take as long as before?

**Comment by mpetroff** [comment]
That's potentially a tremendous waste of bandwidth, which is why it's not built in, particularly when the multires feature allows for scenes to be loaded quickly. That being said, you should be able to load the images yourself using external JavaScript so the browser will already have them cached when the scene is loaded.

**Comment by mpetroff** [comment]
Closing due to lack of response.
