### ISSUE TITLE
How to display initially in full screen?

### ISSUE THREAD

**Issue by thenrich2009** [mpetroff/pannellum#286]
I am not finding a way to do this. If I specify   `  #panorama { width: 100%; height: 100%; }, ` the screen is blank. It seems giving any % to the height, makes the screen blank

and this link displays the image in full screen yet there's no css for the container unless it's in the css file.
https://cdn.pannellum.org/2.3/pannellum.htm#panorama=https://pannellum.org/images/alma.jpg

**Comment by mpetroff** [comment]
The container element already default to 100% width and height, so the CSS you give is completely redundant. If you don't specify a size for the parent element, it will have zero size, since 100% of zero is still zero. You need to make the HTML document body be the size of the screen; take a look at the [CSS used for the standalone viewer](https://github.com/mpetroff/pannellum/blob/master/src/standalone/standalone.css).

**Comment by thenrich2009** [comment]
In your API example at https://pannellum.org/documentation/examples/simple-example/, you have a style for the panorama div. The html and body tags should be 100% by default. The parent of that div is the body. If I remove that style, it doesn't show anything. Why not? If I give 100% width and height to that div, it should be 100% of its parent which is the body.  What am I missing?

**Comment by mpetroff** [comment]
The default height for the `html` and `body` elements is _not_ 100%&mdash;it's the height of the content, which in this case is a `div` without a fixed height set. Therefore, the `body` and the `div` both have a height of zero.

As in the code I linked to previously, you need to set the height of both the `html` element and the `body` element to 100%.
