### ISSUE TITLE
Question about Mobile Version

### ISSUE THREAD

**Issue by andrade94** [mpetroff/pannellum#290]
Hello sir, it's me again, thank you again for all your hard work in this great platform. I have a doubt about what kind of coding you did on the main page of https://pannellum.org/  because when I see it from my desktop it is different for when I see it in my mobile... the icon to change how you see it (by dragging it or moving the phone) appears when you see it from your cellphone and it doesn't appear on the desktop version. How was this done?? On mine it doesn't appear when I open the cellphone version. Thanks in advance.
<img width="48" alt="screen shot 2016-11-16 at 2 47 19 pm" src="https://cloud.githubusercontent.com/assets/7785638/20365191/9eb17c7a-ac0b-11e6-9df7-04e952f2f9e3.png">

**Comment by mpetroff** [comment]
The code that displays the device orientation control toggle starts on line 199 of `pannellum.js`:
https://github.com/mpetroff/pannellum/blob/a30261ca8c68f030f5d7de564d6f252650699c3f/src/js/pannellum.js#L199

It checks if `deviceorientation` events work, and displays the button if they do. Since mobile devices support this and desktop browsers in general don't, it's only displayed on mobile devices. If your instance doesn't display the button, you're probably using an old version; the feature was added in Pannellum 2.3.

**Comment by andrade94** [comment]
Yeah, I'm using it, I got the code in there, but maybe it's not displayed because I got "showControls": false, is there a method to display it with my custom controls with the API? Thanks in advance.

**Comment by mpetroff** [comment]
Hiding the controls will hide the button. There currently isn't an API method to turn device orientation control on or off.

**Comment by tiagoflins** [comment]
Hello! Thank you very much Mr. Petroff for the tool.
I'm not a programmer neither an english speaker. So I hope my best will suffice to ask the question properly.
When I try to display the pannellum through an iframe (the pannellum itself is hosted on another website), the "device orientation button" doesn't appear. Even when I use a smartphone.
Is this a way to always show that button, even when the orientation function is not supported?

Thank you!
