### ISSUE TITLE
newline support in Hotspots

### ISSUE THREAD

**Issue by scottcove** [mpetroff/pannellum#307]
Is it possible to add support for newlines in the hotspot bubble?  I would like dot points seperated by lines, however \n is stripped, and even adding whitespaces is ignored, and will not push the text onto a new line.

**Comment by mpetroff** [comment]
New line characters are meaningless in HTML, which is why they didn't work. Furthermore, HTML is escaped to mitigate XSS attacks, so `<br>` can't be used. Since new lines characters aren't an attack vector, `\n` is now converted to `<br>` after the HTML is escaped, allowing `\n` to be used to insert line breaks.
