### ISSUE TITLE
won't load image

### ISSUE THREAD

**Issue by Mvotre** [mpetroff/pannellum#325]
sorry if it sounds stupid, but I can't make the image work at all. If I set it with a iframe, everything works fine. But if I try with the API (wich I will need because I want to use some hotspots for navigation), the image just keep stuck on loading, or don't load at all. 

http://www.estudiojls.com.br/teste_marcel/JLS/index3.html

in this example, i just copy+paste the entire example on the site, and it don't work anyway... tried a lot of things, but in the best case, I got a spinning block on loading.

**Comment by mpetroff** [comment]
That's because your web server is improperly configured and returns a "200 OK" status code instead of the correct "404 Not Found" code when a file isn't found. If your server was configured correctly, Pannellum would show a helpful error message saying that the image couldn't be loaded.

The configuration you're using specifies the image `/images/bma-1.jpg`, which in your case is http://www.estudiojls.com.br/images/bma-1.jpg. You either need to put an image there or use a different image URL and actually points to an image.
