### ISSUE TITLE
An option to enable mouse wheel zooming only in full screen mode.

### ISSUE THREAD

**Issue by stevenbg** [mpetroff/pannellum#333]
I'm using pannellum to show a panorama embeded in a web page and I set mouseZoom to false, allowing the user to scroll as expected. But when the user clicks the full screen button, the wheel no longer has another function and it is actually expected to zoom.

Sorry if I missed it, but I didn't find an onfullscreen event or a way to change configuration on the fly. Do you think pannellum should have those or a new config option for the described behaviour, which I believe is a common scenario?

**Comment by mpetroff** [comment]
I think changing the available inputs methods depending on whether or not the viewer is fullscreen is quite confusing as far as usability goes, so I'm not sure this is a good idea. I tend to think the default behavior (with `mouseZoom` set to its default value of `true`) is the generally expected behavior, with the scroll wheel zooming the viewer when inside of it and scrolling the page when not over the viewer.

**Comment by mpetroff** [comment]
That's not to say I won't add this, but I would need more convincing before doing so.

**Comment by stevenbg** [comment]
I understand what seems a common scenario to me may not be so common and not worthy of a dedicated option. I suggested it, because while adding fullscreen events and a setConfig method is the better way, especially the latter seems like major work. Since nobody else in 3 years requested changing config on the fly, perhaps it's not worth it.

Currently I can do what I want messing directly with the DOM element of the viewer, which is dirty, but works.

**Comment by mpetroff** [comment]
I thought about this some more. While I'm still not particularly fond of changing available input methods based on whether or not the viewer is fullscreen, I realized I could add the option by changing a single line of code. Starting with b0b7a77cbbfc033338fdd1b6f5c845106088e66d, the `mouseZoom` option can be set to `fullscreenonly` to enable mouse wheel zooming only while fullscreen.

As far as changing the configuration on the fly, this would be complicated to add because different parts of the configuration are processed at different times.

**Comment by stevenbg** [comment]
Hello again!

The way `fullscreenonly` works at the moment is that when you are using the wheel to scroll the page and the cursor comes over the embedded panorama, it won't zoom the panorama, but it won't keep scrolling the page either because you are calling event.preventDefault().

Please see if you can accept my changes.

**Comment by mpetroff** [comment]
Oops; that's what I get for testing with a page that isn't long enough to scroll.

Your pull request dutifully preserves the current behavior of stopping event propagation when the panorama isn't loaded. Now that I think about it, however, this doesn't make much sense to do, so I just moved the `preventDefault()` call to after the conditional return statement in dd4bb363d6c6e5f7919bb1854569d280370ec34f instead of merging your changes that split the checks. Thanks for the pull request, though.
