### ISSUE TITLE
HotSpot onClickHandler prevent default

### ISSUE THREAD

**Issue by BasSilderhuis** [mpetroff/pannellum#342]
Hello,

I have added a clickHandlerFunc to hotspots. At the time of clicking the hotspot I created a popup with options to edit / delete the popup. I just want to call the click event to show the popup and ignore / prevent the normal clicking event of going to the hotspot.

Is it possible to do something like that. In Jquery you can do this with e.preventDefault(). Has Pannellum also an option of ignoring the default hotpsot click action?

**Comment by mpetroff** [comment]
Take a look at the [hot spots example](https://pannellum.org/documentation/examples/hot-spots/). If you use `info` type hot spots (without a URL) instead of `scene` type hot spots, there isn't a default click event to be stopped.

Pannellum doesn't have a "prevent default" option because you should be using hot spots that don't have a click event for something like this.
