### ISSUE TITLE
HotSpot link in same Window?

### ISSUE THREAD

**Issue by marindino1986** [mpetroff/pannellum#386]
When a Hotspot is declared as "type": "scene" then the link will open a new window.
The script is embedded in an iframe. Is it possible to load the link in the same window as the iframe?

thanx in advance!

**Comment by mpetroff** [comment]
The only way to do this without modifying the source code would be to set a custom click handler using the `clickHandlerFunc` hot spot parameter and have that handler set `window.location`. The link target is set to `_blank`, which opens links in a new tab, because the user would lose his or her place in the panorama / tour if the same window was used.

**Comment by OmarNegm** [comment]
would you please share an example here?
