### ISSUE TITLE
Load button hover

### ISSUE THREAD

**Issue by Oreip** [mpetroff/pannellum#40]
Hi there !

At first, I want to thank you for this awesome viewer ! 

I try to customize it, and I have an issue with the "load_button" : when my mouse is hover, sometimes it's working background color change one time and stay freeze even if my mouse is out, and a lot of times nothing  happens.

Do you have a solution for this ?

NB : This issue is with Chrome browser, Firefox is okay

Thank you for reading,

Peter (sorry for my bad english)

**Comment by mpetroff** [comment]
I'm not quite sure what you're asking. Are you talking about the background of the load button getting darker when the mouse is over the button and then returning to its original shade when the mouse leaves?

**Comment by Oreip** [comment]
Yeah, I talking about that.
With Firefox browser, I have no problem with the hover, but with Chrome browser, I have some problems. 
Have you notice this ?

**Comment by mpetroff** [comment]
I have not noticed it, but I also use Firefox most of the time. Since the hover effect is just standard CSS, it's a bug in Chrome, not Pannellum. I found a couple of Chromium bug reports that seem related:

https://code.google.com/p/chromium/issues/detail?id=404368
https://code.google.com/p/chromium/issues/detail?id=399809

**Comment by Oreip** [comment]
Oh, I see.. well.
Anyway, Thank you for reading, and for this free viewer !

Peter
