### ISSUE TITLE
Custom hotspot actions.

### ISSUE THREAD

**Issue by Vortelf** [mpetroff/pannellum#400]
Is there a way to add custom actions, instead of URL, on the hotspots. 
For example I want to make a single-page where I'd like to change the content with AJAX calls.

**Comment by mpetroff** [comment]
Yes. Take a look at the `clickHandlerFunc` and `clickHandlerArgs` hot spot configuration options.

**Comment by kokoruz** [comment]
I'm hoping someone can explain this to me so I better understand how this works.

I am using the clickHandlerFunc and the clickHandlerArgs
`"clickHandlerFunc": videoModal,
"clickHandlerArgs": "video1"`

I created a function call VideoModal but what I don't understand is why my arguments have to be my second parameter?  I couldn't find anything to let me know that.  currently my first parameter of 'modal' is nothing.  I just put it in there to make this work.  I'd really like to understand this better.
`function videoModal(modal, args) {
    var fileName = args;
    if (fileName == "video1") {
        alert("Video 1");
    } else {
        alert("Video 2");
    }  
}`

**Comment by mpetroff** [comment]
Per the configuration reference documentation: "The event object and the contents of `clickHandlerArgs` are passed to the function as arguments." The event object from the `click` event is passed as the first argument, as is documented. If you don't want to use the event object, you don't have to, but you do need a placeholder for it, since the parameters are positional.
