### ISSUE TITLE
Multiple Pannellum Viewers

### ISSUE THREAD

**Issue by nadirhamid** [mpetroff/pannellum#409]
Hello,

Your library is great and we use it a lot for in-house VR tours. 

There is an issue that we have had to "work" around to have the library perform better for
our use case. We display different pannellum viewers on pages and some of these
viewers have the same images. This integration leads to bad load times and usually
duplicating a load.

We tried to work around this by setting a global cache for the images. At first
we tried this outside of the library but we were not able to. It was a better option to make minor
adjustments to the library to support "caching" of the images. 

This currently works for us. But there are still minor issues that could be
resolved. My question to you was whether you plan on making optimizations
to support image "caches" and whether this could be in an updated build. 
I would be very interested in knowing.

Thanks.

**Comment by mpetroff** [comment]
Unless two viewers try to load the same image at the same time, the browser should cache the image after the first time (assuming the server sets the appropriate `Expires` header). Caching is something the browser should handle, not a JavaScript library. Short of keeping multiple images in memory, which is generally a bad idea, I'm not sure what else I could do.

**Comment by nadirhamid** [comment]
Hello,

This was definetly not the case during our tests. Say that we try to initialize the viewer pragmatically, when we tried to display the same images at different times performance did not increase. Your library makes an XHR request to fetch the image and calls a function "parseGPanoXML" the request does not seem to cache.

Is there something I setting wrong in the options and is there something I can do to improve
performance?

**Comment by mpetroff** [comment]
If there's a configuration problem, it's with your server not setting the appropriate caching header. If you load the [title and author example](https://pannellum.org/documentation/examples/title-author/) followed by the [custom controls example](https://pannellum.org/documentation/examples/custom-controls/), the image should be loaded from the browser cache in the second example, since they both use the same image. Note that the transfer size for `alma-correlator-facility.jpg` in the following screenshot is listed as `cached`:

![screenshot](https://user-images.githubusercontent.com/1450212/27101057-41255ada-504e-11e7-8cc3-f91e52edcf33.png)
