### ISSUE TITLE
Mobile: Showing tooltip text on look/focus

### ISSUE THREAD

**Issue by k3lp** [mpetroff/pannellum#415]
Hi,
Quick question. Is it possible to show the hotspots tooltip text when you 'look' at one using the mobile device rotation? Or simply when the tooltip is near the middle of the view? If not, can you maybe give me a pointer on how to implement this?
Kind Regards,

**Comment by mpetroff** [comment]
Take a look at the [custom hot spots](https://pannellum.org/documentation/examples/custom-hot-spots/) example, since it also contains custom tooltips. The tooltips are normally shown using the CSS hover property, so with different CSS (not using the hover property) you can easily create tooltips that show all the time. Showing tooltips just when they are at the center of the view, would be considerably more difficult.
