### ISSUE TITLE
[doc/question] config and panorama parameter

### ISSUE THREAD

**Issue by strarsis** [mpetroff/pannellum#423]
What exactly is the difference between `config` and `panorama` parameters?
`panorama` is meant only for single equirectangular panoramas while 
`config` parameter can be used for a whole tour config file? 
Can an equirectangular panorama loaded by `panorama` parameter also contain `scenes` or `hotSpots`?

**Comment by mpetroff** [comment]
This is already documented:
`config`: https://github.com/mpetroff/pannellum/blob/master/doc/url-config-parameters.md
`panorama`: https://github.com/mpetroff/pannellum/blob/master/doc/json-config-parameters.md#panorama-string

The `panorama` parameter is for a URL to an equirectangular image, while the `config` parameter is for a URL to a JSON configuration file. As the `panorama` parameter is for an image URL, it can't contain anything besides a single image; if you want anything else, you need to use the `panorama` parameter inside a JSON configuration file instead of as a URL parameter.
