### ISSUE TITLE
pannellum locally in iOS

### ISSUE THREAD

**Issue by AlanFloyd** [mpetroff/pannellum#454]
I have installed pannellum (.htm, .css and .js) in the local iOS DocumentsDirectory and able to run the pannellum, saying this, it means the UIWebView shows perfectly the pannellum.

But when trying to load any image (they are also in the DocumentsDirectory) I always get The file file:///var/....jpg could not be accessed.

It is not a question of the JPG, because in Web-Browser on Mac i can see it perfectly.

**Comment by mpetroff** [comment]
This sounds like an iOS, not an issue with Pannellum, possibly a [security restriction](https://stackoverflow.com/questions/33097019/angularjs-on-wkwebview-any-solution-for-handling-file-on-ios-9). Using Safari's remote web debugging might point you in the right direction.

Since Apple forces one to use a Mac for iOS development, I can't help you debug this.

**Comment by AlanFloyd** [comment]
Hi Matthew,

thanks for your message. I have done Safari remote and got the following, see attached screenshot. As you can see, the image is there, but the return code is 0, see the screen on iPhone. What means cod = 0?

Saludos

Dietmar Schwarz Webers
dietmar.schwarz@icloud.com

Desarrollando y Capacitando para iOS
www.dswdev.com

**Comment by mpetroff** [comment]
You need to use GitHub's web interface to add images; your screenshot didn't make it.
