### ISSUE TITLE
Sometimes scene changing occurs an error.

### ISSUE THREAD

**Issue by choiyoonho2** [mpetroff/pannellum#490]
I am using the loadScene function repeatedly to implement animation effects.
I quickly switch to about 15 low resolution scenes.
![code](https://user-images.githubusercontent.com/12508396/30996985-999f8428-a4ff-11e7-9e56-ec50997d890a.JPG)
But sometimes an error occurs in pannellum.js
![code3](https://user-images.githubusercontent.com/12508396/30996994-a9882476-a4ff-11e7-8869-fe4206383026.JPG)
![code2](https://user-images.githubusercontent.com/12508396/30996995-a99fb758-a4ff-11e7-9fbf-4732d6438cf0.JPG)
What is the problem? Is there any other way to implement animation effects while the scene is changing?

**Comment by mpetroff** [comment]
The problem is you're trying to change the scene after 1ms. Even at 60fps, a frame lasts 16.7ms, so this timeout is ridiculously short. You're encountering a race condition because you're trying to change the scene before the first frame finishes rendering. Use a reasonable timeout, say at least 100ms (preferably at least a second), and you shouldn't have this issue.
