### ISSUE TITLE
quick question about smoother transitions

### ISSUE THREAD

**Issue by extropy-** [mpetroff/pannellum#548]
is it possible to (a) turn off loading message and (b) continue rotation during scene fade out?

Great library thanks, and good documentation / examples

**Comment by mpetroff** [comment]
(a) Is you use a [multiresolution panorama](https://pannellum.org/documentation/examples/multiresolution/), there's no loading message. Otherwise, it can't be turned off.
(b) This isn't possible, since the fade is done by saving a rendered frame from WebGL and then fading the captured image; after the fade starts, the original panorama can no longer be rendered.
