### ISSUE TITLE
addScene/loadScene not working as expected

### ISSUE THREAD

**Issue by rfrenz-avio** [mpetroff/pannellum#549]
Hi, I'm trying to adapt the Simple Example to use addScene/loadScene dynamically instead of directly specifying the panorama at creation of the Viewer.

```
<!DOCTYPE HTML>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>A simple example</title>
    <link rel="stylesheet" href="https://cdn.pannellum.org/2.4/pannellum.css"/>
    <script type="text/javascript" src="https://cdn.pannellum.org/2.4/pannellum.js"></script>
    <style>
    #panorama {
        width: 600px;
        height: 400px;
    }
    </style>
</head>
<body>

<div id="panorama"></div>
<script>
var v = pannellum.viewer('panorama', { 'scenes': [], 'autoLoad': true, 'showFullscreenCtrl': false, 'showZoomCtrl': false });
v.addScene('test', {
    "type": "equirectangular",
    "panorama": <my image>
});
v.loadScene('test', 0, 0, 60);
</script>

</body>
</html>
```

When I run this code, I get 'No panorama image was specified', with no errors or 404 in the console.  Can you help me understand what I'm doing wrong?

Cheers,
-Ryan

**Comment by mpetroff** [comment]
The code that prevents race conditions caused by trying to load a new scene while the current scene is still loading was preventing this from working. I fixed this in 2f64204a169e2ca5ae4fc87215f8425ea4f7f1ab.

With the fix, your code should work if you disable `autoLoad` (calling `loadScene` is all that's needed) and changing `scenes` to `{}` from `[]`.

**Comment by rfrenz-avio** [comment]
Thank you very much, it works well now.

**Comment by ZhengYongHe** [comment]
I meet the same problem,and try the way you said,but got another problem:` Cannot read property 'render' of undefined
    at loadScene (pannellum.js:2236)
    at Viewer.loadScene (pannellum.js:2777)`.
Can you help me understand what I'm doing wrong?

**Comment by ZhengYongHe** [comment]
> 我遇到了同样的问题，并尝试你说的方式，但又遇到了另一个问题：` Cannot read property 'render' of undefined at loadScene (pannellum.js:2236) at Viewer.loadScene (pannellum.js:2777)`。
> 你能帮我理解我做错了什么吗？

I have finished it with deleting sceneFadeDuration in the config.

**Comment by ronm123** [comment]
Hi 
first time post here and really liking Pannellum!
I found this thread and am using similar code to that listed above to create scenes dynamically and also using a function to add hotspots. However I can't work out the code/syntax needed to add hotspots to specific scenes. e.g. the scenes dynamically created are sc0, sc1, sc2 etc and like the example above the viewer is v = pannellum.viewer. I'm currently using something like the following to add hotspots:

`v.addHotSpot({"pitch":"-12.8", "yaw":"2.1", "type":"scene","text":"Go to scene 2", "sceneId":"sc2"});`
and
`vn.addHotSpot({"pitch":"-12.8", "yaw":"24.1", "type":"info","text":"text to display as a tooltip", "clickHandlerFunc": x360function,"clickHandlerArgs":"hs2"});`

But the same hotspots are appearing in all of the scenes. What do I need to add to the above so that different hotspots appear in different scenes? 
I'm assuming I need to include the sceneId somehow but I can't get either the code or the syntax correct to achieve that.
Thanks
Ron

**Comment by ronm123** [comment]
Hi
for anyone else reading this thread in future - I was able to target specific scenes by adding comma + sceneId e.g. I have a dynamic variable sc containing the sceneId so:
`vn.addHotSpot({"pitch":"-12.8", "yaw":"24.1", "type":"info","text":"text to display as a tooltip", "clickHandlerFunc": x360function,"clickHandlerArgs":"hs2"},sc);`
