### ISSUE TITLE
Getting Hotspot pitch and yaw

### ISSUE THREAD

**Issue by DingoGhatr** [mpetroff/pannellum#577]
how can i get hotspot pitch and yaw in another function 
            "pitch": 8,
            "yaw": 20,
            "css": "test",
I need this pitch and yaw(8 and 20) in below function
 $(document).on("click", ".test", function() {
	//get pitch and yaw here
});

**Comment by mpetroff** [comment]
Instead of adding the click handler externally, use Pannellum's `clickHandlerFunc` and `clickHandlerArgs` hot spot configuration parameters. You could then use the `clickHandlerArgs` parameter to pass the hot spot's pitch and yaw to your click handler function.

**Comment by DingoGhatr** [comment]
I tried this
  "pitch":8,
  "yaw":  20,
"cssClass": "custom-hotspot2",
"clickHandlerFunc": clickHandlerBox2,
-----------------------------------------------

function clickHandlerBox2(hotSpotDiv, args) {
 var pitch=viewer.getPitch();
var yaw=viewer.getYaw();
}

This one getting values.But the pitch and yaw varying according to the pannellum viewer movement.Is there any way to get that static pitch and yaw values(8 and 20) inside clickHandlerBox2 function?

**Comment by mpetroff** [comment]
The `getPitch` and `getYaw` functions return the current position, so that would be the expected behavior.

You didn't listen to my advice to use the `clickHandlerArgs` parameter. If you set `"clickHandlerArgs": {"pitch": 8, "yaw": 20}"`, you can then access the hot spot's pitch and yaw in your `clickHandlerBox2` function via `args.pitch` and `args.yaw`, receptively.

**Comment by DingoGhatr** [comment]
Thanks for the answer working perfectly.
