### ISSUE TITLE
Video zoomed by default - low quality

### ISSUE THREAD

**Issue by farminf** [mpetroff/pannellum#638]
Hi, 
First of all, big thanks for this beautiful library!
my issue is related to the quality of the video, it seems that by default it zoomed but I cannot really make it zoom out. even the example on pannellum site has low quality than the real video. how can have high quality video? is it something with videojs which I need to fix? because I tried with multi resolution solution of videojs but didn't help.

**Comment by mpetroff** [comment]
4k resolution is the bare minimum for 360 degree video to look decent, with 8k being a considerable improvement over 4k. The example video is 1080p, since that's the highest resolution that the Ricoh Theta S that I have can record. It's not surprising that it looks low quality, but it's no worse than the source video; projecting the equirectangular video has the same effect as zooming in, so it will understandably look lower resolution than viewing the equirectangular video directly. The "fix" is to use higher resolution video.

**Comment by farminf** [comment]
Ok. I understood. Thanks :)

**Comment by farminf** [comment]
Just another thing... when I try to put a high quality video with higher size, I just get the error : "The media could not be loaded, either because the server or network failed or because the format is not supported."
Am I doing something wrong?

**Comment by mpetroff** [comment]
You'd have to look at your browser's developer console. That's a Video.js error message, not a Pannellum one.

**Comment by farminf** [comment]
ok thanks
