### ISSUE TITLE
scaling custom hotspots while zooming

### ISSUE THREAD

**Issue by rrubbico** [mpetroff/pannellum#665]
Hi Matthew,

I have a use case where custom hotspots are used to draw boxes around objects within the viewer. I'm curious if there is a way to intelligently scale these hotspots as the user zooms in/out such that the markup encapsulates a consistent region within the image. Any insight would be much appreciated

Thanks

**Comment by mpetroff** [comment]
This isn't really possible, since the size of an object also depends on where it is in the view, e.g. an object is bigger when it is in the corner than when it is in the center. As for just relative scaling with different horizontal fields of view, it's a simple inverse relationship; when you halve the view of view, you double the size of an object.
