### ISSUE TITLE
Image has a very low resolution in full screen?

### ISSUE THREAD

**Issue by kommunikation** [mpetroff/pannellum#670]
Hi!

Pannellum is great! I'm testing it for the first time and I find it very useful. I have exported an equirectangular image from Blender 3D software and it looks good, but when I click the full screen icon, the image has a very low resolution and it's unsharp. The image resolution is 2000 x 1000 pixel, so it should look better. Do I have to modify the script in some way to also view images in full screen with better quality? I read that there is an option to divide the image into smaller tiles with the help of a Phyton script, but isn't there any other options? I'm just testing Pannellum and want to view the image in full screen for the moment. I don't mind the load time right now. Looking forward to get some help! Thanks!

**Comment by mpetroff** [comment]
The problem is with your image, not the viewer; 2000px across is extremely low resolution for an equirectangular panorama.

With a horizontal field of view of 90 deg, that's only 500px in the view at a time, which is very low compared to the 1920px of a 1080p monitor in full screen. I'd recommend using 4096px, since that's the maximum size supported by most mobile devices in the current release (the next release will double that). If you use the tiled [multiresolution mode](https://pannellum.org/documentation/examples/multiresolution/) instead of just a single image, I'd recommend rendering the image to be ~10000px across.
