### ISSUE TITLE
marking touch and mouse event handler as 'passive'

### ISSUE THREAD

**Issue by meyfleur** [mpetroff/pannellum#673]
i getting following warning chrome:
[Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

would be great if this could be added to fix the warnings

**Comment by mpetroff** [comment]
I'm not going to change this, at least not now.

The "passive" option hijacks previous behavior of `addEventListener`, and browser support was only added around two years ago. Thus, feature detection would be required. Making the event listener passive would have no noticeable effect, since Pannellum's `touchMove` event handler calls `preventDefault()`, negating the "passive" optimization of `touchStart`. Thus, I see no reason to add the feature detection code for the sole purpose of silencing a warning that is only shown when verbose mode is turned on on the Chrome developer console.
