### ISSUE TITLE
VideoJS + samsung browser

### ISSUE THREAD

**Issue by robbeman** [mpetroff/pannellum#678]
When trying to play a video in the samsung browser pannellum shows the "Your browser does not have the necessary WEBGL support to display this panorama" notification. While (according to https://caniuse.com/#feat=webgl) webgl should be supported.

I thought it might've been caused by video encoding, but when I checked on the demo page the issue is there as well.

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/3245659/47567457-e21bdd00-d92e-11e8-9d60-d7840157c1d4.png">
(This is a samsung galaxy S8, with android 7, tested on some other versions as well, only happens in samsung browser, Chrome is fine.)

**Comment by mpetroff** [comment]
Can you access output from the developer console? This should give more information as to what the actual issue is.

The Samsung browser is based on Chromium, so it's odd that Chrome works while the Samsung browser does not.

**Comment by robbeman** [comment]
Hi,

I made a fiddle with some rudimentary loggin, but that doesn't say too much. I get a `console.log` with the following arguments:
```
console.log(
  'Error: Something went wrong with WebGL!',
  1281
);
```

I don't know exactly what that means, but this might hold some clue to you. This is the fiddle I made if you want to dig deeper into this. https://jsfiddle.net/ma0L4n6d/10/

<img width="373" alt="afbeelding" src="https://user-images.githubusercontent.com/3245659/48610009-93d58900-e984-11e8-9a87-74b23806aeff.png">

In any case, thank you for looking into this. (And sorry for the late reply.)

**Comment by mpetroff** [comment]
1281 corresponds to the WebGL `GL_INVALID_VALUE` error, which doesn't help much, since it's a somewhat generic error. Unfortunately, detailed WebGL error messages aren't available through JavaScript. You need the actual developer tools open, where a more detailed message is normally logged by the browser.

BrowerStack claims to [support such developer tools](https://www.browserstack.com/question/660), but I don't see the button mentioned in the documentation in your screen shots. Do you have a physical device on hand that has this issue that you could connect to with [remote debugging](https://samsunginter.net/docs/remote-debugging/) to retrieve the detailed WebGL error message?

**Comment by robbeman** [comment]
Closing this issue because people seem to have forgotten about the project anyway. 🤷‍♂

**Comment by mpetroff** [comment]
Sorry about not replying to to your previous comment. I couldn't think of any reason why adding `gl.getError()` would change anything when I read it but decided to wait to think about it more before responding. Obviously, I then forgot to do so.

Now that I'm revisiting it, I do know why calling `gl.getError()` worked. Calling it clears the error message, so the check at the end of `libpannellum`'s `init` function doesn't see it. It seems that while the browser was throwing a WebGL error, there wasn't actually anything wrong, or at least there was nothing that prevented the panorama from rendering (besides the check that would have otherwise detected that there was an error).

**Comment by robbeman** [comment]
No problem, later on I also noticed that you didn't mention anything about mobile support in the readme, so maybe I am to blame for not reading the docs well enough. 😅

But really thank you for the time you did put into this. I appreciate it.
