### ISSUE TITLE
Unable to open in Safari

### ISSUE THREAD

**Issue by evdelen** [mpetroff/pannellum#68]
I've been exploring using Pannellum in order to display real estate house tours. Unfortunately I've consistently encountered an issue with it displaying in Safari.

I don't use Mac's myself and have never had any issues with Pannellum on either Chrome, Firefox, Opera, or Internet Explore on Windows.

Thanks.

Edit: I'm using the 2.1.0 release.

**Comment by mpetroff** [comment]
Can you be more specific? What version of Safari is affected, and what is the display issue?

**Comment by evdelen** [comment]
Looking around it seems this issue may have already been addressed.

Safari 7.1.4 (9537.85.13.7) on OSX brings up a "your browser doesn't have the necessary WebGL support to display this panorama" error while attempting to display an Equirectangular projection.

**Comment by mpetroff** [comment]
That's the intended behavior. Safari prior to version 8 doesn't support WebGL by default (it can be turned on in the developer menu). Since the CSS 3D transform fallback renderer doesn't support equirectangular panoramas, the error is displayed (the fallback renderer will be used for multires panoramas in version 2.1 and will also be used for cubic panoramas starting with the next release).
