### ISSUE TITLE
How to make a hotspot fixed to a position on the screen Dynamically

### ISSUE THREAD

**Issue by ZhengYongHe** [mpetroff/pannellum#719]
thx for the open source,It help me a lot.   
I wanna know if there's a way to change the hotspot's pitch and yaw dynamically whiling dragging the screen so that the hotspot can fixed to a position on the screen?

**Comment by mpetroff** [comment]
If you just want something fixed in one place on the screen, there's no need to use a hot spot. Just overlay a `<div>` over the viewer as is done by the [custom controls example](https://pannellum.org/documentation/examples/custom-controls/) (there's no reason why the overlays have to be controls).

The only way to update a hot spot is to remove it and then add a new hot spot to replace it. See #684.

**Comment by ZhengYongHe** [comment]
I need  use the hotspots to load another scenes,and wanna it rotate on the plane while rotating the canvas,is there any way to get it?
I have read ur source and add some codes in _onDocumentMouseMove_ but it seems doesn't work... 
thx again!
[新建文本文档 (2).txt](https://github.com/mpetroff/pannellum/files/2973566/2.txt)

**Comment by mpetroff** [comment]
I'm not sure what you mean by "rotate on the plane while rotating the canvas."

**Comment by ZhengYongHe** [comment]
It's like an array of direction hotspots lead to the next place that fixed on the screen while moving the picture .
emmmm...thx anyway.I have solved it by using  the cssClass-`transform` in `render()` and avoid them hiding from moving beyond a certain range
