### ISSUE TITLE
Equirectangular panorama lose quality on mobile browsers.

### ISSUE THREAD

**Issue by danil-farafontov** [mpetroff/pannellum#725]
![Screenshot_2019-04-12-20-48-51-435_com android chrome](https://user-images.githubusercontent.com/2087320/56042100-76a2bc00-5d64-11e9-85b6-f715986a21ca.png)
Image getting pixelated/blurred.
https://pannellum.org/documentation/examples/auto-rotate/
You can see it in example from documentation.

Device used - Xiaomi Redmi Note 3
OS - Android 6.0.1
Browser - Chrome 73.0.3683.90

**Comment by mpetroff** [comment]
There have been previous reports of this sort of pixelized behavior (#301, #496, #683, #708), but I had never been able to reproduce it, which made it difficult to figure out the cause. This time, however, I was finally able to reproduce it, probably because I replaced my mobile phone last year. I ended up tracking it down to a WebGL fragment shader precision issue, which I fixed in 59893bcea4629be059ad3e59c3fa5bde438d292b (at least for Chrome / Firefox on a Sony XZ1 Compact).
