### ISSUE TITLE
Add html and image in tool tip ?

### ISSUE THREAD

**Issue by micker** [mpetroff/pannellum#734]
hello i try to add image in tool tip but seems doesn't work can you html me ?

`],
            "hotSpots": [
                {
                    "pitch": -12,
                    "yaw": 170,
                    "type": "info",
                    "text": "This is Jordan Pond, located in Acadia National Park."
                },
                {
                    "pitch": -10,
                    "yaw": -50,
                    "type": "info",
                    "text": "<img src='bag360.jpg'><br/> Youpi !",
                    "URL": "https://github.com/mpetroff/pannellum"
                },
                {
                    "pitch": 0,
                    "yaw": -60,
                    "type": "scene",
                    "text": "Pond",
                    "sceneId": "pond"
                }
            ]
        },
`

**Comment by mpetroff** [comment]
HTML is escaped unless you explicitly set the `escapeHTML` parameter to `false`, to mitigate against potential DOM XSS attacks. However, depending on what you're doing, you many want to look at the [custom hot spots example](https://pannellum.org/documentation/examples/custom-hot-spots/), since it demonstrates the use of custom tool tips.
