### ISSUE TITLE
WebGL support no support

### ISSUE THREAD

**Issue by artefakte** [mpetroff/pannellum#737]
Hi... the pannellum works awesome in (win-opera)browser, but i experience a bit strange behaviour on my mobile.
so simple panoramas i "did" with the minified standalone viewer, CSS, and JavaScript... via URL do not show up, due to "your browser does not have...GL support..."
I know one can enable GL in chrome://flags - but actually your panorama on the frontpage (the library) works quite well with default settings, so does the video example.
Just the "a simple example" is also not working.
Is there anything special about your frontpage panorama, which lets it work without issues in the mobile chrome? some kind of magic? :D thanks for your great work.

**Comment by mpetroff** [comment]
The homepage panorama is a [multiresolution panorama](https://pannellum.org/documentation/examples/multiresolution/), which falls back to a CSS-based renderer when WebGL doesn't work.

However, since the video example works, I suspect that your mobile device doesn't support WebGL textures larger than 2048px (this is unusual, since the vast majority of devices support textures up to at least 4096px); the video resolution is 1920px. Since the multiresolution panoramas are tiled into smaller images, the homepage example probably still works using WebGL, since the individual textures are small enough.

If you're using Chrome / Firefox on mobile (I'm assuming you're using Android), you can attach the device using USB and use the developer tools of the corresponding Desktop browser to see the exact error.
