### ISSUE TITLE
Hotspot clickHandlerFunc not called when scene type

### ISSUE THREAD

**Issue by willcalderbank** [mpetroff/pannellum#745]
Hotspot `clickHandlerFunc` is not called when then hopspot  type is `scene`

I believe the `div.onclick` assignment blocks the event from the addEventListener although I could be wrong.

[https://github.com/mpetroff/pannellum/blob/master/src/js/pannellum.js#L1723](url)

**Comment by mpetroff** [comment]
I can't reproduce this behavior with the Git `master` version of Pannellum in recent versions of Firefox or Chromium. The `clickHandlerFunc` is called but after the scene change starts, since the scene change event handler is added first.

If you want more control over this ordering, I'd recommend calling `loadScene` directly from your `clickHandlerFunc` instead of using a `scene` hot spot.

**Comment by willcalderbank** [comment]
Thank you, thats what I ended up doing.
