### ISSUE TITLE
SCRIPT5022: TypeMismatchError with IE11 and SPFx Webpart

### ISSUE THREAD

**Issue by MasterZydra** [mpetroff/pannellum#752]
When using Pannellum in a SPFx WebPart in the IE11, an error occurs. In the developer tools I can see that the picture is loaded. It stops with the fully loaded loading bar.
```
SCRIPT5022: TypeMismatchError
BaseURL.ts (16,7)
```
I have already asked on StackOverFlow but it seems that nobody has used it in that way before.
https://stackoverflow.com/questions/57004448/using-spfx-webpart-with-ie11-sharepoint-2016-and-pannellum

**Comment by mpetroff** [comment]
That error message isn't from Pannellum, and it has something to do with SharePoint, since Pannellum works fine in IE 11 for normal webpages.

As I see it, you have two options. You could replace Pannellum's single use of `createObjectURL` with the IE-specific function suggested on StackOverflow, or you could modify your `BaseURL.ts` file to skip type checking / cast to the correct type (I assume TypeScript lets you do that, having never used it).

As noted in the readme, app frameworks such as this are not officially supported and are not tested (but often work).

**Comment by MasterZydra** [comment]
Thanks for the fast reply.  
I have tried to replace `createObjectURL` with `window.navigator.msSaveOrOpenBlob()`. The problem is that with that function the bar shows up and asks if I want so save or open it.  
I have not found BaseURL.ts in the webpart. It seems to be a part of nodeJS or so.  

I have found a working solution for me. I used the standalone.js and iframe and that worked. Currently I am extending the standalone.js so it supports compass, hotSpotDebugging... and hotSpots

**Comment by mpetroff** [comment]
I'm glad you found something that works. I have no idea where the `BaseURL.ts` file comes from, just that it isn't part of Pannellum.

**Comment by MasterZydra** [comment]
The problem with IE could not be solved. Even with other panorama viewer the combination of Internet Explorer 11, SPFx Webpart and SharePoint 2016 is not working. All other browsers are working without problems. I think it has to do with the HTML5 compatibility and extreme strict behavior with security.
