### ISSUE TITLE
Native way to not fade out the hotspots or alternative objects placed in the scenes.

### ISSUE THREAD

**Issue by martinlombana** [mpetroff/pannellum#758]
When changing to another scene, I noticed that the hotspots fade out first, and then the rest of the scene fades out.  

Is there any way to keep the hotSpots and avoid them fading? I actually used one hotSpot to create a round circle in the floor, always in the center, at pitch=-90, yaw=90, to hide the tripod. 

On another note, is there any supported or already thought way to add a "non hot-spot" object that behaves like them, so I can accomplish the "round circle" in the middle, for instance?. 

I also need to add other objects in the scenes, dynamically. 

![image](https://user-images.githubusercontent.com/18351919/61671992-2c799100-acea-11e9-8afe-5be134e479ac.png)

Thanks!

**Comment by mpetroff** [comment]
The fade works by taking a snapshot of the WebGL canvas and fading it out. Since the hot spots are not rendered using WebGL, having them match the panorama fade is not supported; adding such support would require significant changes.

[Custom hot spots](https://pannellum.org/documentation/examples/custom-hot-spots/) would allow you to add hot spot-like objects, although I'm guessing you already found that. These can be added / removed dynamically using the `addHotSpot` / `removeHotSpot` methods.
