### ISSUE TITLE
Pannellum: autoload problem

### ISSUE THREAD

**Issue by nivekyee831** [mpetroff/pannellum#782]
Hi,

I'm using the autoload sample found in "https://pannellum.org/documentation/examples/auto-load/", I try to add a link, and only by clicking on the link, then the image inside a div section will pop up.   If the autoload = true, then I found the image have problem loading, only if you click on the enlarge button then the image will shown correctly.

Sample of the code below, I just amend a little bit for the window popup.

<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="WebForm1.aspx.cs" Inherits="pannellum3.WebForm1" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Auto load</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/pannellum@2.5.2/build/pannellum.css"/>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/pannellum@2.5.2/build/pannellum.js"></script>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <style>
    #panorama {
        width: 600px;
        height: 400px;
    }
    </style>
</head>
<body>
<a id="link1" href="#">link</a> 
<div id="panorama" style="display:none;"></div>
<script>
pannellum.viewer('panorama', {
    "type": "equirectangular",
    "panorama": "https://pannellum.org/images/cerro-toco-0.jpg",
    "autoRotate": -2,
    "autoLoad": true
});
</script>

<script>
        $(document).on("click", "a", function () {
            
            $("#panorama").dialog();
           // $("#panorama").show();
        //alert("here");
        //$("#photosphere").show();
         });
</script>

</body>
</html>

**Comment by mpetroff** [comment]
Next time, please include a complete example and don't include C# code, which is completely irrelevant.

While your code snippet doesn't include it, I'm assuming you're creating the Pannellum viewer with the `#panorama` `<div>` hidden, with the CSS `display` property set to `none`. This means that the `<div>` has a size of zero when it's created, which is why the panorama doesn't display. Either create the viewer with a visible element, or assign the viewer to a variable, e.g., `var viewer = pannellum.viewer(...)` and call `viewer.resize()` when you display it so it will use the displayed size.

**Comment by nivekyee831** [comment]
Hi,

Thanks for your advice, I try assign the viewer to a variable and resize it when displayed, it works fine, thank you very much.
