### ISSUE TITLE
Pannellum 2.5.3 - 6080 x 3040 images just shown as black on iPhone 6 iOS 12.4

### ISSUE THREAD

**Issue by DStillingfleet** [mpetroff/pannellum#785]
Hi Matthew

Just a little feedback regarding 2.5.3 supporting images larger than 4096 x 2048 pixels by splitting them into two smaller images.

It was a feature I was very excited about, but does not appear to be working on my iPhone 6 with iOS 12.4.  I made a test using a 6080 x 3040 image, but is just shows a black screen, see [https://www.virtualmountains.co.uk/X/2_5_3_Test.html](https://www.virtualmountains.co.uk/X/2_5_3_Test.html).

It works fine on a PC which was happy to display larger panoramas.

If you want any extra info, let me know.

Kind regards

Derek

**Comment by mpetroff** [comment]
It seems that the WebGL texture size limits also apply to the size of non-WebGL `<canvas>` elements. From the developer console (iOS simulator, via Saucelabs), a warning (which isn't detectable from JavaScript):

> Canvas area exceeds the maximum limit (width * height > 16777216).

This should be fixable be using a smaller `<canvas>` and drawing the image twice, once each at different offsets, instead of what is currently being done, which is to make a `<canvas>` the size of the image, draw the image once, and then create WebGL texture from sub-regions of the `<canvas>`.

**Comment by mpetroff** [comment]
I think I've fixed the issue, but I don't have a physical device to test on (the fix works on the iOS simulator).

@DStillingfleet Can you see if https://mpetroff.net/files/iostest/ works for you? If it does, I'll push the changes and remove the test from my server.

**Comment by DStillingfleet** [comment]
Hi Matthew 


Yes, you’ve fixed it.  It’s working 👍.


Best wishes and many thanks 


Derek

**Comment by mpetroff** [comment]
Fixed in c3cf33a5db6b160a514e4fb31d20dc91550a9838. I'm considering temporarily backing out df4c45dd332921b96fb3fa021cdab4dd06f75d96 and releasing 2.5.4, since this is a silent failure, and that commit is the only significant change since 2.5.3.

**Comment by DStillingfleet** [comment]
Sounds like a good idea.

**Comment by DStillingfleet** [comment]
Excellent, thank you. Some Virtual English Tea on it’s way.😄
