### ISSUE TITLE
numerical targetYaw is ignored - patch provided

### ISSUE THREAD

**Issue by trumpton** [mpetroff/pannellum#79]
The version currently in the GIT repository (as cloned 20150615) ignores the targetPitch and targetYaw if they are set numerically (e.g. not set to 'same').  I believe this is down to a missing condition.  The patch below adds this back in:

It would be good to be able to orient all scenes with the northOffset, and then be able to view the current heading with the debug, and set hotspots with real-life pitch and yaw coordinates (i.e. taking the northOffset into consderation) - this would mean modifying how the debug yaw is shown, and how the hotspots are placed - do you have a view / strategy on how you want this to work, and I can have a go at a patch to satisfy?

Steve

```
diff -Naur pannellum-20150615/src/js/pannellum.js pannellum/src/js/pannellum.js
--- pannellum-20150615/src/js/pannellum.js	2015-06-15 20:54:46.349197445 +0100
+++ pannellum/src/js/pannellum.js	2015-06-15 21:11:24.093152961 +0100
@@ -1452,11 +1452,15 @@
     // Set new pointing
     if (targetPitch === 'same') {
         workingPitch = config.pitch;
+    } else {
+	workingPitch = targetPitch ;
     }
     if (targetYaw === 'same') {
         workingYaw = config.yaw;
     } else if (targetYaw === 'sameAzimuth') {
         workingYaw = config.yaw + config.northOffset - tourConfig.scenes[sceneId].northOffset;
+    } else {
+	workingYaw = targetYaw ;
     }
     
     // Destroy hot spots from previous scene
```

**Comment by mpetroff** [comment]
With regards to using the north offset for yaw coordinates, I'm not really sure I see much of a benefit, since it's an easy conversion to do by hand. While adding this feature would make things easier in some cases, it has the downside of adding complexity, being yet another feature that needs to be maintained. This bug itself is an example of how unrelated changes can easily break lesser used features (although I really need to add a test suite at some point to catch this kind of thing).

Another possibility to obtain the results of the feature you're suggesting would be a rather simple script that modifies the panorama itself to center north horizontally.
