### ISSUE TITLE
I have a little bit of an issue with additional URL parameter from my server

### ISSUE THREAD

**Issue by hl24a3** [mpetroff/pannellum#807]
Hi, it's not an issue with your panorama per se but you might be able to help

- I'm using the standalone version of your viewer
- My free web hosting is always adding additional parameter at the end of every URL **/?i=1** and this causes the pannelum viewer to display the following error **An invalid configuration parameter was specified: i**
- So instead of **server.com** I always get **server.com/?i=1**
- I've found sort of a workaround with **.httaccess** rewrite to remove it but it not always works for unknown reason and additionally when I remove this parameter from every URL, my image gallery doesn't want to load images.
- Is there a way to make pannelum standalone to ignore this parameter?

Thanks

**Comment by mpetroff** [comment]
How are you specifying the URL parameters? The preferred method is to use `#` instead of `?`, since this avoids sending the parameters to the server. When `#` is used, the standalone viewer should ignore any parameters specified with `?`. The following two examples work fine for me:

https://cdn.pannellum.org/2.5/pannellum.htm?i=1#panorama=https://pannellum.org/images/alma.jpg
https://cdn.pannellum.org/2.5/pannellum.htm#panorama=https://pannellum.org/images/alma.jpg?i=1

**Comment by hl24a3** [comment]
This is how my panorama is specified

`http://www.xxxx.com/pannellum.htm#panorama=http://www.xxxx.com/panorama.jpg&autoLoad=true&autoRotate=2`

I use fancybox gallery and the whole one item looks like this

`<a data-fancybox="pano" data-type="iframe" href="http://www.xxxx.com/pannellum.htm#panorama=http://www.xxxx.com/gallery/panorama.jpg&autoLoad=true&autoRotate=2" data-caption="<div class='captionTitle'>Panorama title</div>"></a>`

I have no control over this /?i=1 it gets added by the webhost automatically so I really don't even know in which part of the URL it gets added

**Comment by mpetroff** [comment]
Without looking at the actual network traffic, I'm not sure I can really debug this more. Pannellum _should_ ignore the `?=1` if `#` is used, so I can't think of an obvious reason why it isn't working in your case.
