### ISSUE TITLE
Different panning on desktop than mobile

### ISSUE THREAD

**Issue by 360fusionBen** [mpetroff/pannellum#83]
I was wondering if it would be possible to to have two different ways to navigate?

On desktop - I would like to click and move my mouse to the right to pan but be able to hold it and the panorama pans around to the right continuously without having to move my mouse again.

On mobile/tablet - This would be fine just the way it is, drag your finger on the panorama from left to right and the panorama pans right.

This would be similar to how krpano works which is quite good for user experience. I know Google maps works with the click and move on desktop but I find the krpano way better.

Also, I just wanted to say I love what you're doing. keep up the good work.

**Comment by mpetroff** [comment]
This is something I considered more seriously a few years ago but eventually decided against. I originally implemented the click and drag method as that is my preference, as I use the arrow keys when I want more continuous navigation. In the panorama community everyone has a preference as for which navigation method is better. However, I think the current click and drag method is more intuitive to the general public due to the proliferation of touch screen devices. I'm not entirely against having the krpano-like navigation as an option, but I don't think I'll ever add it myself as I would like to keep the user experience consistent across devices and websites using Pannellum.
