### ISSUE TITLE
Failed to execute 'readAsBinaryString' on 'FileReader': parameter 1 is not of type 'Blob'.

### ISSUE THREAD

**Issue by 531431988** [mpetroff/pannellum#845]
![image](https://user-images.githubusercontent.com/8703951/77147554-7c526700-6ac8-11ea-8ebd-9a04b020619d.png)
![image](https://user-images.githubusercontent.com/8703951/77147550-78bee000-6ac8-11ea-85d3-37168bc1777e.png)
一直报这个错，不知道为什么

**Comment by mpetroff** [comment]
You're not providing enough information to be useful. What browser / OS are you using?

You appear to be using some sort of framework. Note that per the readme "mobile / app frameworks are not officially supported."

This issue tracker is in English. Please make an attempt to report all issues in English.

**Comment by 531431988** [comment]
window 10
chrome
vue cli3

**Comment by mpetroff** [comment]
It seems that whatever you're doing to produce a `MockXMLHttpRequest` instead of a normal, standards-compliant `XMLHttpRequest` is causing problems by not returning a response that can be read by [`FileReader.readAsBinaryString`](https://developer.mozilla.org/en-US/docs/Web/API/FileReader/readAsBinaryString). As this is a framework issue, and frameworks are not officially supported, I'm closing this issue.

**Comment by blowROCK** [comment]
I think, this issue window image cache.
1. 5 megabytes image is work fine.
2. when the remaining capacity of the C drive is small, Problem encountered.
3. It's working well in Mac. 

solution
var img = new Blob([this.respones]);
xhr.responseType='arraybuffer'; 

works for me.
