### ISSUE TITLE
TARGA/BMP output format from multires script

### ISSUE THREAD

**Issue by strarsis** [mpetroff/pannellum#847]
The multires script supports JPEG and PNG as output formats although the underlying Python PIL/Pillow library supports other output formats like TARGA/BMP. 
For improving the compression yield, a JPEG encoder can be used. Most of these recommend uncompressed input data in Bitmap (TARGA) format.
For allowing this the multires script just needs a `BMP`/`TARGA` option.

**Comment by mpetroff** [comment]
As PNG uses lossless compression, it works just fine as input to an optimized JPEG encoder. It's generally slightly slower to write than an uncompressed image, but this extra time is insignificant when compared to the overhead of using an optimized JPEG encoder such as [Guetzli](https://github.com/google/guetzli). An uncompressed TIFF file is a better alternative to BMP/TGA anyway, since it's an actual ISO standard.

**Comment by strarsis** [comment]
@mpetroff: Hm, I will try to make the jpeg encoders (mozjpeg, gruetzli) work with PNG/TIFF input.
Other image formats than JPEG and Bitmaps/TARGA don't seem to be supported by these encoders.

**Comment by mpetroff** [comment]
Looking at their documentation, MozJPEG supports JPEG, PNG, BMP, and TGA input, while Guetzli supports JPEG and PNG.

I've personally used PNG input with Guetzli, so I know that works.

**Comment by strarsis** [comment]
@mpetroff: OK, I will try PNG as input.
