### ISSUE TITLE
Why do high-resolution panoramas choose cube grid instead of spherical grid？

### ISSUE THREAD

**Issue by hopepdm** [mpetroff/pannellum#868]
Can't we choose the equirectangular  panorama as the texture of the spherical mesh and make the high-definition panorama？

**Comment by mpetroff** [comment]
Spherical meshes are inaccurate because spheres are not made of planar faces; a spherical mesh is an approximation. This is why Pannellum's equirectangular mode does not use a mesh and instead does a [proper projection](https://github.com/mpetroff/pannellum/blob/master/doc/pannellum-equirectangular-projection-reference.pdf), which prevents [nadir and zenith artifacts](https://threejs.org/examples/webgl_panorama_equirectangular.html) among other distortions. The equirectangular projection itself is only used because it is a de facto standard for spherical panoramas, likely due to its simplicity. It has extremely high area and angle distortions, which leads to much larger images than would otherwise be necessary. Thus, since the multiresolution mode requires the image to be processed anyway, it doesn't make any sense to use the equirectangular format.

Pannellum's multiresolution format is based on a cube map projection in an attempt to maintain compatibility with the tiled panoramas used by the Flash-based panorama viewers that were in widespread use when it was created. These viewers used a cube map projection because it is also a simple projection, which is probably the easiest projection to implement a viewer for with a 3D graphics API. While the cube map projection is more efficient than an equirectangular projection, it is still far from optimal.

Ideally, an equal area projection with relatively low angular distortion would be used. At some point, I want to implement such a projection, likely based on an octahedron.

**Comment by hopepdm** [comment]
@mpetroff  thanks for your answer.
