### ISSUE TITLE
add header div

### ISSUE THREAD

**Issue by valeriodeluca** [mpetroff/pannellum#869]
Hi there,
I'd like add a trasparent overlay header div like this:
http://www.mainjoin.eu/vt/pannellum/examples/3_marzipano

I tried it like this but doesn't work:

htm:
```
<div class="header">
  Header
</div>
```
pannellum.css:
```
.header {
  position: absolute;
  left: 0px;
  top: 0px;
  z-index: 10000;
  padding: 5px;
  text-align: center;
  background: #1abc9c;
  color: white;
  font-size: 15px;
}
```

tks

**Comment by mpetroff** [comment]
1. This is far from a complete example, so it tells me very little.
2. There's no reason to put your own CSS into `pannellum.css` instead of your own CSS file.
3. The [custom controls example](https://pannellum.org/documentation/examples/custom-controls/) shows how to add custom elements to the viewer.

**Comment by valeriodeluca** [comment]
Ok it works with css inside own.css:
```
.header {
  position: absolute;
  left: 0px;
  right:40px;
  top: 0px;
  height: 40px;
  z-index: 10000;
  padding: 5px;
  text-align: center;
  background: rgba(58,68,84,0.8);
  color: white;
  line-height: 30px;
}
```

In htm I suggest put the header div inside panorama div, so when it goes fullscreen header don't disappear.
