### ISSUE TITLE
Can't create multires panoramas.

### ISSUE THREAD

**Issue by fclaudino** [mpetroff/pannellum#87]
Could anyone help me?

I've been trying to create multires panoramas but i haven't been successful so far.

When i'm trying to run "python generate.py examplepano.jpg" i get the error below:
![error1](https://cloud.githubusercontent.com/assets/2853444/9365414/cf35803e-4687-11e5-9510-0622831f0d63.png)

Then i tried run the follow code: "python generate.py examplepano.jpg -n/--nona", and got this error:
![error2](https://cloud.githubusercontent.com/assets/2853444/9365421/d6b97d92-4687-11e5-8ed8-7ae49e863930.png)

>> [WinError 2] O sistema não pode encontrar o arquivo especificado, MEANS:
 "[WinError 2]  The system can't find the specified  file " 

Any thoughts?

Thx!!!

**Comment by mpetroff** [comment]
Since `nona` isn't on your system path, you need to specify its location with the `-n` flag, e.g. `python generate.py -n "C:\Program Files\Hugin\bin\nona.exe" examplepano.jpg` (obviously the path for `nona` might be different on your system, so use the appropriate path). The error lists `-n/--nona` since `--nona` could also be used instead of `-n`.

**Comment by fclaudino** [comment]
Works like a charm! 
Huge thanks!

Great script , by the way. ;)
