### ISSUE TITLE
remove zoom button

### ISSUE THREAD

**Issue by valeriodeluca** [mpetroff/pannellum#870]
Hi,
Is there a way to remove zoom-in/zoom-out button ("+/-" ) and fullscreen.
I want only remove the button but leave the default possibility to zoom in zoom out.
Thanks

**Comment by valeriodeluca** [comment]
The way that I found at moment it's to comment pannellum.css from line 101 to 128:
```
/*.pnlm-zoom-controls {
    width: 26px;
    height: 52px;
}

.pnlm-zoom-in {
    width: 100%;
    height: 50%;
    position: absolute;
    top: 0;
    border-radius: 3px 3px 0 0;
}

.pnlm-zoom-out {
    width: 100%;
    height: 50%;
    position: absolute;
    bottom: 0;
    background-position: 0 -26px;
    border-top: 1px solid #ddd;
    border-top-color: rgba(0,0,0,0.10);
    border-radius: 0 0 3px 3px;
}

.pnlm-fullscreen-toggle-button, .pnlm-orientation-button, .pnlm-hot-spot-debug-indicator {
    width: 26px;
    height: 26px;
}*/
```

**Comment by mpetroff** [comment]
Please read the documentation more closely. There's a `showControls` configuration parameter that can be used to hide all of the controls, as well as a `showZoomCtrl` parameter and a `showFullscreenCtrl` parameter, which can be used to selectively hide the controls.

**Comment by franpr09** [comment]
Hi, I have the same problem. I've changed those values, but it keeps coming out...
![image](https://user-images.githubusercontent.com/70898127/92388565-c8957000-f117-11ea-810f-b63d6f672181.png)

**Comment by mpetroff** [comment]
@franpr09 You're going to need to be a bit more specific. What do you mean by "it keeps coming out"? Setting `showControls: false` will hide the zoom and fullscreen buttons. A working example is also much easier to debug than a screenshot of some subset of your code.

**Comment by franpr09** [comment]
@mpetroff  first, sorry for my English. I downloaded Pannellum from your website. I moved the folder to my server, and in that folder, I modified the `showControls: false` parameter of the "pannellum.js" file, but the controls still appear. This is the test that I am using "infotour360.es/test.html"

**Comment by mpetroff** [comment]
Okay, this makes a lot more sense now.

You're using the `pannellum.htm` file, which is separate from the `pannellum.js` / `pannellum.css` files. Thus, editing the `pannellum.js` has no effect.

Regardless, you should not edit the provided files and should instead specify the changes in your configuration. If you want to continue using `pannellum.htm` in an `<iframe>`, you need to create a JSON configuration file and point Pannellum at it, e.g., create a file called `yourconfig.json` with the following contents
```json
{
  "panorama": "https://i.imgur.com/tFp6WdE.jpg",
  "autoLoad": true,
  "autoRotate": 8,
  "showControls": false
}
```
and upload it to your server; then point Pannellum at it with `pannellum.htm#config=yourconfig.json` (you'll have to use a different path if you don't place the JSON file in the same directory as the `pannellum.htm` file). The `showControls` parameter is an advanced option that can't be changed using URL parameters, which is why the JSON configuration file needs to be used.
