### ISSUE TITLE
setting Hfov - getting issues

### ISSUE THREAD

**Issue by SimonT1972** [mpetroff/pannellum#879]
**Firstly - I'd like to say THANK YOU to the creator for such an amazing bit of software.**

I am using a resize function to detect screen width and height, and setting a HFOV as 120 for landscape and 50 for portrait layouts.

This kinda works although there are a few kinks in it.  Sometimes the resize function is called and the correct HFOV is called to be set, but when I use getHfov it returns what looks like the default HFOV.  Sometimes it works, sometimes it doesn't.  

Code is below:
```javascript
function ReSize() {
	// Get screen size (inner/outerWidth, inner/outerHeight)
	var height = window.innerHeight;
	var width = window.innerWidth;
	if(width<height) {
	  // portrait
		panne.setHfov(50); 
		alert("setting HFOV to 50 - value was set at "+panne.getHfov());
	} else {
	  // landscape (or width=height)
		panne.setHfov(120);
		alert("setting HFOV to 120 - value was set at "+panne.getHfov());
	}
// for a bit of screen visual showing of the HFOV	
document.getElementById('hfov').value = panne.getHfov();
}
```

![image](https://user-images.githubusercontent.com/66754236/84323617-09a8d300-ab6f-11ea-8165-dd54b50eff37.png)

**Comment by mpetroff** [comment]
If you don't set the `animated` parameter of the `setHfov` method call to `false` (or `0`), it defaults to an animated transition with a duration of one second. Thus, if you call `getHfov()` immediately after, you'll get the original HFOV, since it's still the current HFOV, as the viewer has not yet transitioned to the new HFOV. The `getHfov` call returns the current HFOV, not the HFOV targeted by the transition.

**Comment by SimonT1972** [comment]
That's brilliant - set the hfov with (50, animated=false) and it worked a treat.  I did wonder why it worked sometimes and not others.  

Thanks for your quick help and for producing such amazing software (and ongoings support).
