### ISSUE TITLE
Hide background image while loading

### ISSUE THREAD

**Issue by kial1** [mpetroff/pannellum#884]
Hello,

I am using the
`.pnlm-load-box {
   z-index:-999;
   opacity: 0;
}`
css tag to hide the loading bar (Or is there any other methode?).

But then how can I change the background image?

Greetings

**Comment by mpetroff** [comment]
The easiest way is to use the `preview` configuration parameter (see [example](https://pannellum.org/documentation/examples/preview-image/)). Otherwise, the background is set via the `background` property of the `.pnlm-container` CSS class.

https://github.com/mpetroff/pannellum/blob/1f9f0cd3fd9f14bd9007713e03dbb1f47b9557d6/src/css/pannellum.css#L1-L10

**Comment by noushad-alternative-agency** [comment]
.pnlm-container {
  background: #fff !important;
}

**Comment by AndreyPatseiko** [comment]
I hide background with this style:
```
#panorama.pnlm-container {
    background-image: none;
    background-color: transparent;
}
```
