### ISSUE TITLE
 the code  to open the page to show cross-domain

### ISSUE THREAD

**Issue by ziji1224054593** [mpetroff/pannellum#888]
the code  to open the page to show cross-domain
代码拉取下来后，打开tests.html文件显示跨域

**Comment by ziji1224054593** [comment]
本地图片页是跨域
Local image pages are cross-domain

**Comment by mpetroff** [comment]
This issue tracker is in English, so please make an attempt to use it, even if that involves relying on machine translation.

That being said, I ran what you wrote through Google Translate, and I have absolute no idea what you're asking. What you've written appears to me to be an incomplete thought. Please include more details and possibly a screenshot or two.

**Comment by ziji1224054593** [comment]
Access to XMLHttpRequest at 'http://www.ycktest.com/Public/images/base.jpg?id=603' from origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by ziji1224054593** [comment]
"panorama": "./static/base.jpg",
Access to XMLHttpRequest at 'file:///D:/Users/Desktop/112233/static./static/base.jpg?id=905' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.

**Comment by mpetroff** [comment]
The error messages say exactly what is wrong. You are making cross-domain requests without [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) configured on your server. You need to either configure CORS or host the images on the same domain as the page you're trying to access them from.

In the second case, you're having issues because you're trying to access a file on the local filesystem, which is something that is blocked by web browser security restrictions. Quoting from Pannellum's readme: "Due to browser security restrictions, a web server must be used locally as well."

**Comment by ziji1224054593** [comment]
非常感谢，问题已解决

**Comment by mpetroff** [comment]
I'm glad I was able to help.
