### ISSUE TITLE
Request:  lat/lon in pannellum

### ISSUE THREAD

**Issue by mrAceT** [mpetroff/pannellum#889]
Hi,

First of all, my complements for your nifty piece of code!

Second, could you add support in jour pannellum for (more) lan/lon control?

I would love the ability to be able to ad a hotspot based upon a latitude and longitude, also I'dd love to be able to get a (click) event of the mouse over the panorama giving me a lat/lon pair.

Is there any chance you could add something like that?

**Comment by mpetroff** [comment]
This is already possible; however, the terms pitch / yaw are used instead of latitude / longitude.

These are the coordinates that are used in the JSON configuration to specify the location of hot spots. To get the coordinates when you click, you need to add a `mousedown` event listener using the `viewer.on` API method and then in your event listener function pass the event object to the `viewer.mouseEventToCoords` method to get the pitch / yaw.

**Comment by mrAceT** [comment]
Awesome! (didn't find that in the documentation (link?)

PS: is it also possible to draw a line with lat/lon?

**Comment by mpetroff** [comment]
Drawing lines is not possible.

Hot spot configuration:
https://pannellum.org/documentation/reference/#hotspots-object

Converting mouse events to coordinates:
https://pannellum.org/documentation/api/#mouseeventtocoords

Adding event listeners:
https://pannellum.org/documentation/api/#on
