### ISSUE TITLE
Extraneous sign in custom hotspots

### ISSUE THREAD

**Issue by Riclim** [mpetroff/pannellum#896]
Hello,
Why the class `pnlm-sprite` is added to the custom hotspot wrapper? It draws a "+" where should be only a user defined hotspot, right? What is the best solution to remove it without damage the navigation buttons? 
Thank you

**Comment by mpetroff** [comment]
It's not added to custom hot spots. When you set a custom hot spot style with the `cssClass` hot spot parameter, the hot spot is assigned that class instead of `pnlm-sprite` and `pnlm-hotspot`. See, e.g., the [custom hot spots example](https://pannellum.org/documentation/examples/custom-hot-spots/).
