### ISSUE TITLE
360 Video Resolution Bug in Chrome.

### ISSUE THREAD

**Issue by Vicarium** [mpetroff/pannellum#897]
Changing to fullscreen and back in chrome causes the resolution of the non-fullscreen video to distort.

You can see this in the video example, https://pannellum.org/documentation/examples/video/

**Comment by mpetroff** [comment]
The issue is that Chrome reports the wrong size for the viewer when it is checked in the `fullscreenchange` event handler after existing full screen. I'd argue that this is a browser bug, but I was able to work around it using the relatively new [ResizeObserver interface](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver) and fix this in 44e878f30763a51cbbbf5ab4c5b97fa4c3b2dfd9.

**Comment by Vicarium** [comment]
Awesome! That was a crazy fast fix, thanks.
