### ISSUE TITLE
Change multiRes panorama based on <select> dropdown menu (JSON files)

### ISSUE THREAD

**Issue by Jaumen90** [mpetroff/pannellum#909]
Hi,

I'm working on a solution that allows to change the panorama by using dropdown menu. I found some solution at this link:

https://stackoverflow.com/questions/55845145/change-image-in-javascript-based-on-select-dropdown

The issue is that it works for jpeg/png files. I need the same but for JSON file instead of JPEG (for multiRES panorama read by JSON file and for virtual tour). 

How can I change the script to make this solution for this purpose?

Thank you for any support in this case.

**Comment by mpetroff** [comment]
Create a [tour](https://pannellum.org/documentation/examples/tour/) with all your images, which do not need to be linked with hot spots. When creating the Pannellum viewer, assign it to a variable, e.g., `var viewer = pannellum.viewer(...);`. Then call `viewer.loadScene(target_scene_id);` in your select change event handler, where `target_scene_id` is the scene ID of the panorama you want to load, to switch the panorama.

The answers to that Stack Overflow question are all very much sub-optimal, since they destroy and recreate the Pannellum viewer each time, which requires destroying and recreating the WebGL context. That being said, the answers will work for multiresolution images if you just change the Pannellum configuration being used to use `"type": "multires"` and your corresponding multiresolution configuration instead of `"type": "equirectangular"`.
