### ISSUE TITLE
Can I prevent double-click zoom? 

### ISSUE THREAD

**Issue by 2001hcy** [mpetroff/pannellum#914]
Hi Mattew :) 

Can I prevent zoom with double-click?
I've tried `stopPropagation` or `preventDefault` with `mousedown` event listener, but it didn't meet my expectations. 

There are any solutions?

**Comment by mpetroff** [comment]
You need to set the [`doubleClickZoom`](https://github.com/mpetroff/pannellum/blob/master/doc/json-config-parameters.md#doubleclickzoom-boolean) parameter to `false`. This parameter was undocumented until recently (see #842), which is why it's not in the pannellum.org documentation (which is only updated with new releases).

**Comment by 2001hcy** [comment]
Thanks :)
