### ISSUE TITLE
minPitch and maxPitch calculation should take zoom level as a parameter

### ISSUE THREAD

**Issue by justin-lau** [mpetroff/pannellum#92]
Currently the `minPitch` and `maxPitch` restrict the angle of the viewer regardless of the zoom level. i.e. if the `minPitch` and `maxPitch` are both set to `0`, the viewer center is locked vertically when the viewer zooms in.

**Comment by mpetroff** [comment]
That's how the parameters are defined, so of course the view center is locked if `minPitch` and `maxPitch` are set to the same value. Implementing the behavior you suggest would be nice, but it's a lot more complicated. Both zoom level and viewer size need to be taken into account, and a behavior needs to be decided on for what happens when the viewer is resized. I though about adding this, but it's not currently high on my list of priorities.

**Comment by justin-lau** [comment]
Hi @mpetroff, thanks for the quick reply. I'm very new to pannellum. I just think the current behaviour is unnatural to the users. It's good to know that you plan to work on it. I would like to contribute on it too when I can spare the time, but I haven't worked on computer graphics for 3 years, so it might take a while ;-)

**Comment by jannecederberg** [comment]
@justin-lau do you want to test?

**Comment by mpetroff** [comment]
I just changed the `minPitch` and `maxPitch` limits such that they apply to the edge of the viewer instead of the center and take zoom into account.
