### ISSUE TITLE
Viewer suddenly freezes

### ISSUE THREAD

**Issue by strarsis** [mpetroff/pannellum#935]
With build from Pannellum master, when looking around in the panorama, the viewer freezes with a JavaScript error:
````
Uncaught TypeError: Cannot set property 'texture' of undefined
````
The panorama is a multires panorama, also generated with the Pannellum multires generation too.
All image files can be downloaded, there are no HTTP errors.
Apparently the freeze occurs when changing the pitch too fast.

**Comment by mpetroff** [comment]
Good catch! I was easily able to reproduce the issue from your observation about rapidly changing the viewer pitch.

This looks like it was caused by race condition in the performance improvements I made to resolve #911. I added a simple check to make sure the node is defined before trying to set its attributes in 50ea593a096eec7dc5a120189cd8b5132617bcf6, which seems to have resolved the issue.
