### ISSUE TITLE
Supported image formats

### ISSUE THREAD

**Issue by lmmurtuza** [mpetroff/pannellum#938]
Hi,

I have just started using pannellum. I just wanted to know things for client documentation:

- Image formats that are supported

- Min/Max image resolution

- Min/Max image size

**Comment by mpetroff** [comment]
> Image formats that are supported

Pannellum supports whatever image formats your web browser does.

> Min/Max image resolution

This depends on which mode you're using. For `equirectangular` images, I'd recommend keeping the image width below 8192px, since not all devices support higher resolutions (the limitation is due to WebGL texture size limits). For `multires` images, the max resolution is effectively unlimited. I guess the minimum resolution is a 1px square, although an image that small would be kind of useless.

> Min/Max image size

How is this any different than image resolution?
