### ISSUE TITLE
Facebook "fbclid" interfering with page loading

### ISSUE THREAD

**Issue by SMU-Meadows** [mpetroff/pannellum#939]
Hi Matthew, I am a huge fan of your work and am extremely thankful for everything you've done on Pannellum.

When I try to post a link to a Pannellum-based 360 panorama on Facebook, FB automatically adds an "&fbclid=###" parameter to the end of the url on click, which causes the page to load with the error "An invalid configuration parameter was specified: fbclid". Since I am not super knowledgeable about CS (I just used your examples and documentation to figure out how to implement Pannellum's features to accomplish my objectives), I have no idea how to get around this and be able to post a link directly to a 360 photo on FB. Any ideas?

Thanks again Matthew!

**Comment by mpetroff** [comment]
The only way without making modifications to Pannellum itself is to not use the standalone version (at least not directly). Creating a separate HTML file for each panorama using the API version will prevent URL parameters from affecting things.

The code that triggers the error is:
https://github.com/mpetroff/pannellum/blob/9ccf60b88e255dc853c081ce976e77d626dea952/src/standalone/standalone.js#L44-L46

Deleting / commenting out those line would disable the check.

I think the check is rather useful, so I don't want to remove it. I would also rather not add a special case just because Facebook's adware doesn't behave, but I think this might be the only usable solution. I'll have to think about it more.

**Comment by mpetroff** [comment]
As discovered in #965, specifying Pannellum's parameters as a location hash, i.e., using `#` instead of `?`, resolves this issue. Since using `#` is the preferred method, anyway, since it doesn't unnecessarily send the configuration parameters to the server, I consider this issue resolved.
