### ISSUE TITLE
iPhone X crashing in Safari with Canvas area exceeds the maximum limit

### ISSUE THREAD

**Issue by fluidadsjtr** [mpetroff/pannellum#973]
I have a tour consisting of two images, both images are the same size (6912 x 3456 jfif/jpg).

Because the images are the same size it does not matter which I load first, clicking an hotspot to load the image in landscape causes no problems, but in portrait mode gives Canvas area exceeds the maximum limit (width * height > 16777216) pannellum.js:441

Here is the tour https://johnvirtualtours.s3.eu-west-2.amazonaws.com/Prop_1615918414705/tour.html

This error does not happen with Chrome on iPhone X.

**Comment by mpetroff** [comment]
Although I don't have a recent iOS device to test with (so I can't reproduce the issue), this sounds like a bug in Safari. Changing between landscape and portrait shouldn't affect anything. Furthermore Chrome on iOS (as with any other browser on iOS) is exactly the same as Safari except with a different user interface, since Apple does not allow alternative browser rendering engines.

That being said, I do have some ideas on how to work around what is likely a browser bug. However, you'll have to do the testing, since I don't have an appropriate device to test with. I'm also assuming you meant to write `libpannellum.js:441` instead of `pannellum.js:441` for the error line, since the former would make sense but the latter does not. My best guess based on the error is that Safari is not using the default standard `<canvas>` size of 300px x 150px and instead sizing the `<canvas>` based on the view dimensions (this would explain the portrait / landscape difference). Try adding the following two lines just before `libpannellum.js:441` (between the `var cropCanvas = document.createElement('canvas');` and `cropCanvas.width = image.width / 2;` lines):
```javascript
console.log(cropCanvas.width, cropCanvas.height, image.width / 2, image.height);
cropCanvas.width = cropCanvas.height = 150;
```
The first line will log the original canvas and image dimensions, which should provide the data necessary to confirm or reject my hypothesis (please post the result). The second line should fix the issue, by resetting the `<canvas>` dimensions, if my hypothesis is correct.

**Comment by fluidadsjtr** [comment]
}
                    if (!c.drawInProgress) {
                        c.drawInProgress = !0;
                        a.clear(a.COLOR_BUFFER_BIT);
                        for (g = 0; g < c.currentNodes.length; g++)
                            1 < c.currentNodes[g].textureLoaded && (a.bindBuffer(a.ARRAY_BUFFER, Fa), a.bufferData(a.ARRAY_BUFFER, new Float32Array(c.currentNodes[g].vertices), a.STATIC_DRAW), a.vertexAttribPointer(c.vertPosLocation,
                            3, a.FLOAT, !1, 0, 0), a.bindBuffer(a.ARRAY_BUFFER, Y), a.vertexAttribPointer(c.texCoordLocation, 2, a.FLOAT, !1, 0, 0), a.bindTexture(a.TEXTURE_2D, c.currentNodes[g].texture), a.drawElements(a.TRIANGLES, 6, a.UNSIGNED_SHORT, 0));
                        c.drawInProgress = !1
                    }
                }
                if (s.returnImage !== p)
                    return A.toDataURL("image/png")    <--- Canvas area exceeds the maximum limit (width * height > 16777216)
            } else
                for (l = $ / 2, s = {
                    f: "translate3d(-" + (l + 2) + "px, -" + (l + 2) + "px, -" + l + "px)",
                    b: "translate3d(" + (l + 2) + "px, -" + (l + 2) + "px, " + l + "px) rotateX(180deg) rotateZ(180deg)",
                    u: "translate3d(-" + (l + 2) + "px, -" + l + "px, " + (l + 2) + "px) rotateX(270deg)",
                    d: "translate3d(-" + (l + 2) + "px, " + l + "px, -" + (l + 2) + "px) rotateX(90deg)",
                    l: "translate3d(-" + l + "px, -" + (l + 2) + "px, " + (l + 2) + "px) rotateX(180deg) rotateY(90deg) rotateZ(180deg)",
                    r: "translate3d(" + l + "px, -" + (l + 2) + "px, -" + (l + 2) + "px) rotateY(270deg)"
                }, k = 1 / Math.tan(k / 2), k = k * A.clientWidth / 2 + "px", e = "perspective(" + k + ") translateZ(" + k + ") rotateX(" + g + "rad) rotateY(" + e + "rad) ", k = Object.keys(s), g = 0; 6 > g; g++)
                    if (h = R.querySelector(".pnlm-" + k[g] + "face"))
                        h.style.webkitTransform = e + s[k[g]],
                        h.style.transform = e + s[k[g]]

**Comment by fluidadsjtr** [comment]
Above is the code when I view from Safari debugger line with error is 
return A.toDataURL("image/png")    <--- Canvas area exceeds the maximum limit (width * height > 16777216)

**Comment by fluidadsjtr** [comment]
The html contains 2892 * 5856 = 16935552, I don't understand why loading the first image doesn't complain.  Javascript is my weakest language but I have a developer I work with and he is excellent so we can answer any questions.

<div class="pnlm-render-container"><canvas width="2892" height="5856" style="height: 100%; width: 100%;"></canvas><div class="pnlm-hotspot-base pnlm-hotspot pnlm-sprite-hotspots pnlm-scene pnlm-pointer pnlm-tooltip" style="visibility: visible; transform: translate(459.4999999999999px, 953.5px) translateZ(9999px) rotate(0deg);"><span class=" pnlm-pointer" style="width: 64px; margin-left: -19.5px; margin-top: -66px;">kitchen 2</span></div></div>

**Comment by mpetroff** [comment]
Okay, so the line number you reported was meaningless. It was whatever Safari assigned after expanding the minified code. Ignore what I previous said; the line number you reported and the error message coincidentally made some sense in the context of the current source of `libpannellum.js`.

Your problem is that you're not setting up the viewport properly, so the view is being rendered at much higher resolution than screen resolution (2436px x 1125px for the iPhone X). Adding `<meta name="viewport" content="width=device-width, initial-scale=1.0">` to your page's `<head>` section, just below `<meta charset="utf-8">` (as is done in the Pannellum [examples](https://pannellum.org/documentation/examples/simple-example/)) will fix this; it will also improve performance and make the Pannellum user interface elements a much more reasonable size.

If you didn't set the `sceneFadeDuration` parameter, you wouldn't have experienced the issue. The issue is being triggered by the section of code that captures the current view in order to fade to the next scene. That's why you don't have an issue when loading the first image (and why it has nothing to do with the image resolution).

**Comment by fluidadsjtr** [comment]
Thank you for your support sorry our incorrect usage caused you time to investigate.
