### ISSUE TITLE
full screen not working when embedded in Blackboard 9.1

### ISSUE THREAD

**Issue by sijpkes** [mpetroff/pannellum#98]
Hi Matthew Petroff, couldn't work out how to contact you directly so I hope this gets in.  Great job on the tool btw! This is an issue when embedding as an iframe in the Blackboard LMS, the fullscreen button doesn't work but the zoom buttons do work.

**Comment by mpetroff** [comment]
My best guess is that the `allowfullscreen` attribute is missing from the `iframe`. In Firefox, this results in "Request for full-screen was denied because at least one of the document's containing iframes does not have an 'allowfullscreen' attribute." being printed in the Web Console (Chrome doesn't seem to print a message).

**Comment by sijpkes** [comment]
Yep, that looks like it!  Good guess... now to work out a hack to change the native iframe generated by Blackboard.  I'll post it when I figure it out!

**Comment by sijpkes** [comment]
To solve this issue place this in a script tag somewhere in the page containing panellum's iframe.

`(function () {
    var iframe = parent.document.getElementById("contentFrame");
    if (typeof iframe !== 'undefined') {
        if (iframe !== null) {
            iframe.setAttribute("allowfullscreen", "allowfullscreen");
        }
    }
})();`
