### ISSUE TITLE
mulires black flicker on image load issue

### ISSUE THREAD

**Issue by webuilderkrish** [mpetroff/pannellum#985]
hello

i know that #911 is closed and i also tried 
`    this.isBaseLoaded = function() {
        if (program.currentNodes.length >= 6) {
            for (var i = 0; i < 6; i++) {
                if (!program.currentNodes[i].textureLoaded) {
                    return false;
                }
            }
            return true;
        }
        return false;
    }`

above  code but it seems not working and the black flicker is looking horrible can you please get me an another  way to fix the issue

**Comment by mpetroff** [comment]
@webuilderkrish Are you and @fluidadsjtr working together? If so, please discuss things among yourselves and pick a single person to ask questions instead of asking the same question multiple times from different accounts.

Regardless, I'd like to keep the discussion on this in one place, so I'm closing this issue in favor of continuing the discussion in #912. If you read the rest of my comment where that code snippet came from, https://github.com/mpetroff/pannellum/issues/912#issuecomment-833974460, you'd know that the code snippet isn't a complete solution. It's just a method for determining if the base tiles have finished loading. You'd have to make other changes, that call the function, for it to actually do anything.
